import WebSocket from 'ws';import {pcmu8kToPcm16k,pcmToPcmu8k} from './telephonyCodec.js';import type {RealtimeCallbacks,RealtimeConfig,RealtimeProvider} from './types.js';
type NimEvent={type?:string;delta?:string;transcript?:string;audio?:string;item_id?:string;error?:{message?:string}};
type ChatMessage={role:'system'|'user'|'assistant';content:string};
function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name} is not configured`);return value.replace(/\/$/,'')}
function wsUrl(base:string,intent:string){const url=new URL(base);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname='/v1/realtime';url.search=`intent=${intent}`;return url.toString()}
export class NvidiaRealtimeProvider implements RealtimeProvider{
 private asr?:WebSocket;private tts?:WebSocket;private ready=false;private pending:string[]=[];private busy=false;private history:ChatMessage[];
 constructor(private config:RealtimeConfig,private callbacks:RealtimeCallbacks){this.history=[{role:'system',content:config.instructions}]}
 async connect(){const asrBase=required('NVIDIA_ASR_NIM_URL');const ttsBase=required('NVIDIA_TTS_NIM_URL');const [asrToken,ttsToken]=await Promise.all([this.mint(asrBase,'transcription_sessions'),this.mint(ttsBase,'synthesis_sessions')]);this.asr=await this.open(wsUrl(asrBase,'transcription'),asrToken);this.tts=await this.open(wsUrl(ttsBase,'synthesize'),ttsToken);this.asr.on('message',raw=>this.handleAsr(raw.toString()));this.tts.on('message',raw=>this.handleTts(raw.toString()));const language=process.env.NVIDIA_ASR_LANGUAGE??'en-US';this.send(this.asr,{type:'transcription_session.update',session:{modalities:['text'],input_audio_format:'pcm16',input_audio_transcription:{language,model:process.env.NVIDIA_ASR_MODEL??'conformer',prompt:''},input_audio_params:{sample_rate_hz:16000,num_channels:1},recognition_config:{max_alternatives:1,enable_automatic_punctuation:true,enable_word_time_offsets:false,enable_profanity_filter:false,enable_verbatim_transcripts:false},speaker_diarization:{enable_speaker_diarization:false,max_speaker_count:1},word_boosting:{enable_word_boosting:false,word_boosting_list:[]},endpointing_config:{start_history:0,start_threshold:0,stop_history:0,stop_threshold:0,stop_history_eou:0,stop_threshold_eou:0}}});this.send(this.tts,{type:'synthesize_session.update',session:{input_text_synthesis:{language_code:process.env.NVIDIA_TTS_LANGUAGE??language,voice_name:this.config.voice||null},output_audio_params:{sample_rate_hz:Number(process.env.NVIDIA_TTS_SAMPLE_RATE??22050),num_channels:1,audio_format:'LINEAR_PCM'},custom_dictionary:'',custom_configuration:{flush:'true'}}});this.ready=true;for(const audio of this.pending.splice(0))this.appendAudio(audio);this.callbacks.onReady()}
 appendAudio(audio:string){if(!this.ready){if(this.pending.length<250)this.pending.push(audio);return}this.send(this.asr,{type:'input_audio_buffer.append',audio:pcmu8kToPcm16k(audio)})}
 close(){this.ready=false;this.pending=[];this.asr?.close(1000,'call ended');this.tts?.close(1000,'call ended')}
 private async mint(base:string,path:string){const key=process.env.NVIDIA_REALTIME_MINT_API_KEY;const headers:Record<string,string>={};if(key)headers.Authorization=`Bearer ${key}`;const response=await fetch(`${base}/v1/realtime/${path}`,{method:'POST',headers});if(!response.ok)throw new Error(`NVIDIA NIM mint failed: ${response.status}`);const json=await response.json() as {client_secret?:{value?:string}|null};return json.client_secret?.value}
 private open(url:string,token?:string){return new Promise<WebSocket>((resolve,reject)=>{const protocols=token?['realtime',`realtime-token.${token}`]:undefined;const ws=new WebSocket(url,protocols);ws.once('open',()=>resolve(ws));ws.once('error',reject);ws.on('error',e=>this.callbacks.onError(e));ws.on('close',(code,reason)=>{if(code!==1000)this.callbacks.onError(new Error(`NVIDIA NIM closed (${code}): ${reason.toString()}`))})})}
 private send(socket:WebSocket|undefined,event:Record<string,unknown>){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(event))}
 private handleAsr(raw:string){let e:NimEvent;try{e=JSON.parse(raw) as NimEvent}catch{return this.callbacks.onError(new Error('NVIDIA ASR returned invalid JSON'))}if(e.type==='conversation.item.input_audio_transcription.delta'&&e.delta)this.callbacks.onTranscript({speaker:'caller',text:e.delta,final:false,providerItemId:e.item_id});else if(e.type==='conversation.item.input_audio_transcription.completed'&&e.transcript){this.callbacks.onTranscript({speaker:'caller',text:e.transcript,final:true,providerItemId:e.item_id});void this.respond(e.transcript)}else if(e.type==='error')this.callbacks.onError(new Error(e.error?.message??'NVIDIA ASR error'))}
 private handleTts(raw:string){let e:NimEvent;try{e=JSON.parse(raw) as NimEvent}catch{return this.callbacks.onError(new Error('NVIDIA TTS returned invalid JSON'))}if(e.type==='conversation.item.speech.data'&&e.audio)this.callbacks.onAudio(pcmToPcmu8k(e.audio,Number(process.env.NVIDIA_TTS_SAMPLE_RATE??22050)));else if(e.type==='conversation.item.speech.completed')this.callbacks.onEvent('response.done',{});else if(e.type==='error')this.callbacks.onError(new Error(e.error?.message??'NVIDIA TTS error'))}
 private async respond(text:string){if(this.busy||!text.trim())return;this.busy=true;try{this.callbacks.onInterruption();this.history.push({role:'user',content:text});const base=required('NVIDIA_LLM_NIM_URL');const key=process.env.NVIDIA_LLM_API_KEY;const response=await fetch(`${base}/v1/chat/completions`,{method:'POST',headers:{'content-type':'application/json',...(key?{Authorization:`Bearer ${key}`}:{})},body:JSON.stringify({model:process.env.NVIDIA_LLM_MODEL??'meta/llama-3.1-8b-instruct',messages:this.history,temperature:0.4,max_tokens:220})});if(!response.ok)throw new Error(`NVIDIA LLM failed: ${response.status}`);const json=await response.json() as {choices?:Array<{message?:{content?:string}}>} ;const answer=json.choices?.[0]?.message?.content?.trim();if(!answer)throw new Error('NVIDIA LLM returned no answer');this.history.push({role:'assistant',content:answer});if(this.history.length>21)this.history.splice(1,2);this.callbacks.onTranscript({speaker:'ai',text:answer,final:true});this.send(this.tts,{type:'input_text.append',text:answer});this.send(this.tts,{type:'input_text.commit'});this.callbacks.onEvent('response.created',{})}catch(error){this.callbacks.onError(error instanceof Error?error:new Error('NVIDIA pipeline failed'))}finally{this.busy=false}}
}
