import WebSocket from 'ws';
import type {RealtimeCallbacks,RealtimeConfig,RealtimeProvider} from './types.js';
type ServerEvent=Record<string,unknown>&{type?:string;delta?:string;transcript?:string;item_id?:string};
const voices=new Set(['alloy','ash','ballad','coral','echo','sage','shimmer','verse','marin','cedar']);
export class OpenAIRealtimeProvider implements RealtimeProvider{
 private socket?:WebSocket;private ready=false;private pending:string[]=[];
 constructor(private config:RealtimeConfig,private callbacks:RealtimeCallbacks){}
 connect():Promise<void>{const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return Promise.reject(new Error('OPENAI_API_KEY is not configured'));const model=process.env.OPENAI_REALTIME_MODEL??'gpt-realtime-2.1';this.socket=new WebSocket(`wss://api.openai.com/v1/realtime?model=${encodeURIComponent(model)}`,{headers:{Authorization:`Bearer ${apiKey}`,'OpenAI-Safety-Identifier':this.config.safetyIdentifier}});return new Promise((resolve,reject)=>{const initial=(e:Error)=>reject(e);this.socket!.once('error',initial);this.socket!.once('open',()=>{this.socket!.off('error',initial);this.socket!.on('error',e=>this.callbacks.onError(e));this.socket!.on('message',raw=>this.handle(raw.toString()));this.socket!.on('close',(code,reason)=>{this.ready=false;if(code!==1000)this.callbacks.onError(new Error(`OpenAI Realtime closed (${code}): ${reason.toString()}`))});this.send({type:'session.update',session:{type:'realtime',model,output_modalities:['audio'],instructions:this.config.instructions,audio:{input:{format:{type:'audio/pcmu'},turn_detection:{type:'server_vad'}},output:{format:{type:'audio/pcmu'},voice:voices.has(this.config.voice)?this.config.voice:'marin'}}}});this.ready=true;for(const audio of this.pending.splice(0))this.appendAudio(audio);this.callbacks.onReady();resolve()})})}
 appendAudio(audio:string){if(!this.ready){if(this.pending.length<250)this.pending.push(audio);return}this.send({type:'input_audio_buffer.append',audio})}
 close(){this.ready=false;this.pending=[];this.socket?.close(1000,'call ended')}
 private send(event:Record<string,unknown>){if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify(event))}
 private handle(raw:string){let e:ServerEvent;try{e=JSON.parse(raw) as ServerEvent}catch{this.callbacks.onError(new Error('OpenAI Realtime returned invalid JSON'));return}const type=e.type??'unknown';if(type==='response.output_audio.delta'&&typeof e.delta==='string')this.callbacks.onAudio(e.delta);else if(type==='response.output_audio_transcript.delta'&&typeof e.delta==='string')this.callbacks.onTranscript({speaker:'ai',text:e.delta,final:false,providerItemId:e.item_id});else if(type==='response.output_audio_transcript.done'&&typeof e.transcript==='string')this.callbacks.onTranscript({speaker:'ai',text:e.transcript,final:true,providerItemId:e.item_id});else if(type==='conversation.item.input_audio_transcription.completed'&&typeof e.transcript==='string')this.callbacks.onTranscript({speaker:'caller',text:e.transcript,final:true,providerItemId:e.item_id});else if(type==='input_audio_buffer.speech_started')this.callbacks.onInterruption();else if(type==='error')this.callbacks.onError(new Error(JSON.stringify(e.error??e)));if(['session.created','session.updated','response.created','response.done','rate_limits.updated'].includes(type))this.callbacks.onEvent(type,e)}
}
