import {pool,withTenant,closeDatabase} from './database.js';
import {assertPublicHttps} from './knowledge.js';
import {integrationSignature,resolveSecret} from './integrations.js';

const owner=process.env.AUTOMATION_WORKER_ID??`automation-${process.pid}`;
const pollMs=Math.max(250,Number(process.env.AUTOMATION_WORKER_POLL_MS??1000));
let running=true;
export function retryDelaySeconds(attempt:number){return Math.min(3600,Math.max(5,5*2**Math.max(0,attempt-1)))}

type Job={id:string;connection_id:string;event_type:string;payload:Record<string,unknown>;attempts:number;created_at:Date};
async function claim(tenantId:string){return withTenant(tenantId,async c=>{const row=(await c.query<Job>(`WITH candidate AS(SELECT id FROM automation_jobs WHERE (state='queued' AND available_at<=now()) OR (state='processing' AND lease_until<now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE automation_jobs j SET state='processing',attempts=attempts+1,lease_owner=$1,lease_until=now()+interval '90 seconds',last_error=NULL FROM candidate WHERE j.id=candidate.id RETURNING j.id,j.connection_id,j.event_type,j.payload,j.attempts,j.created_at`,[owner])).rows[0];return row??null})}
async function finish(tenantId:string,job:Job){await withTenant(tenantId,async c=>{const connection=(await c.query(`SELECT kind,endpoint_url,secret_ref,status FROM automation_connections WHERE id=$1`,[job.connection_id])).rows[0];if(!connection||connection.status!=='active')throw new Error('integration is not active');await assertPublicHttps(connection.endpoint_url);const timestamp=String(Math.floor(Date.now()/1000));const body=JSON.stringify({id:job.id,eventType:job.event_type,kind:connection.kind,occurredAt:job.created_at.toISOString(),payload:job.payload});const response=await fetch(connection.endpoint_url,{method:'POST',headers:{'content-type':'application/json','user-agent':'Llamar-Integration/1.0','x-llamar-event-id':job.id,'x-llamar-timestamp':timestamp,'x-llamar-signature':integrationSignature(resolveSecret(connection.secret_ref),timestamp,body)},body,signal:AbortSignal.timeout(15000)});if(!response.ok)throw Object.assign(new Error(`endpoint returned ${response.status}`),{responseCode:response.status});await c.query(`UPDATE automation_jobs SET state='delivered',delivered_at=now(),lease_owner=NULL,lease_until=NULL,response_code=$2 WHERE id=$1 AND lease_owner=$3`,[job.id,response.status,owner])})}
async function fail(tenantId:string,job:Job,error:unknown){const message=(error instanceof Error?error.message:'delivery failed').slice(0,1000);const responseCode=typeof error==='object'&&error&&'responseCode'in error?Number((error as {responseCode:unknown}).responseCode):null;await withTenant(tenantId,c=>c.query(`UPDATE automation_jobs SET state=CASE WHEN attempts>=8 THEN 'failed' ELSE 'queued' END,available_at=now()+make_interval(secs=>$2),lease_owner=NULL,lease_until=NULL,last_error=$3,response_code=$4 WHERE id=$1 AND lease_owner=$5`,[job.id,retryDelaySeconds(job.attempts),message,responseCode,owner]).then(()=>undefined))}
export async function processTenant(tenantId:string){const job=await claim(tenantId);if(!job)return false;try{await finish(tenantId,job)}catch(error){await fail(tenantId,job,error)}return true}
async function loop(){while(running){const tenants=(await pool.query<{id:string}>(`SELECT id FROM tenants WHERE status='active' ORDER BY id`)).rows;let worked=false;for(const tenant of tenants)worked=(await processTenant(tenant.id))||worked;if(!worked)await new Promise(resolve=>setTimeout(resolve,pollMs))}}
async function shutdown(){running=false;await closeDatabase()}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
if(process.argv[1]?.endsWith('automationWorker.js'))loop().catch(async error=>{console.error(error);await closeDatabase();process.exitCode=1});
