import {z} from 'zod';import type pg from 'pg';
const E164=z.string().regex(/^\+[1-9]\d{6,14}$/);
export const DidRequestCreate=z.object({requestedNumber:E164.nullable().default(null),provider:z.string().min(2).max(80),requestType:z.enum(['new','change']),documentObjectKey:z.string().min(3).max(500),documentSha256:z.string().regex(/^[a-f0-9]{64}$/i)});
export const DidReview=z.object({tenantId:z.string().uuid(),decision:z.enum(['approved','rejected']),reviewNote:z.string().min(3).max(1000),did:E164.optional()});
export const DidDirectAssign=z.object({tenantId:z.string().uuid(),did:E164,provider:z.string().min(2).max(80),reason:z.string().min(5).max(1000)});
export const DidFlowBind=z.object({flowId:z.string().uuid(),flowVersion:z.number().int().positive()});
export async function listDidRequests(client:pg.PoolClient){return {items:(await client.query(`SELECT id,requested_number AS "requestedNumber",provider,request_type AS "requestType",status,review_note AS "reviewNote",reviewed_at AS "reviewedAt",created_at AS "createdAt" FROM did_requests ORDER BY created_at DESC LIMIT 200`)).rows}}
export async function listDidAssignments(client:pg.PoolClient){return {items:(await client.query(`SELECT d.id,d.did,d.provider,d.active,d.assignment_mode AS "assignmentMode",d.source_request_id AS "sourceRequestId",d.created_at AS "createdAt",b.flow_id AS "flowId",b.flow_version AS "flowVersion",f.name AS "flowName" FROM did_assignments d LEFT JOIN did_flow_bindings b ON b.did_assignment_id=d.id AND b.active LEFT JOIN flows f ON f.id=b.flow_id ORDER BY d.created_at DESC LIMIT 200`)).rows}}
export async function createDidRequest(client:pg.PoolClient,tenantId:string,input:z.infer<typeof DidRequestCreate>,actorId:string){const r=await client.query(`INSERT INTO did_requests(tenant_id,requested_number,provider,request_type,document_object_key,document_sha256) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,requested_number AS "requestedNumber",provider,request_type AS "requestType",status,created_at AS "createdAt"`,[tenantId,input.requestedNumber,input.provider,input.requestType,input.documentObjectKey,input.documentSha256]);await client.query(`INSERT INTO audit_events(tenant_id,actor_id,action,resource_type,resource_id,payload) VALUES($1,$2,'did_request.created','did_request',$3,$4::jsonb)`,[tenantId,actorId,r.rows[0].id,JSON.stringify({provider:input.provider,requestType:input.requestType})]);return r.rows[0]}
export async function reviewDidRequest(client:pg.PoolClient,id:string,input:z.infer<typeof DidReview>,actorId:string){const current=await client.query(`SELECT id,requested_number,provider,status FROM did_requests WHERE id=$1 FOR UPDATE`,[id]);const item=current.rows[0];if(!item||item.status!=='pending')throw new Error('DID request is not pending');if(input.decision==='approved'){const did=input.did??item.requested_number;if(!did)throw new Error('approved DID is required');await client.query(`INSERT INTO did_assignments(tenant_id,did,provider,source_request_id,assigned_by,assignment_mode) VALUES($1,$2,$3,$4,$5,'approved_request')`,[input.tenantId,did,item.provider,id,actorId])}await client.query(`UPDATE did_requests SET status=$2,reviewed_by=$3,review_note=$4,reviewed_at=now() WHERE id=$1`,[id,input.decision,actorId,input.reviewNote]);await client.query(`INSERT INTO audit_events(tenant_id,actor_id,action,resource_type,resource_id,payload) VALUES($1,$2,$3,'did_request',$4,$5::jsonb)`,[input.tenantId,actorId,`did_request.${input.decision}`,id,JSON.stringify({reviewNote:input.reviewNote})]);return {id,status:input.decision}}
export async function directAssign(client:pg.PoolClient,input:z.infer<typeof DidDirectAssign>,actorId:string){const r=await client.query(`INSERT INTO did_assignments(tenant_id,did,provider,assigned_by,assignment_mode) VALUES($1,$2,$3,$4,'platform_admin_direct') RETURNING id,did,provider,active,created_at AS "createdAt"`,[input.tenantId,input.did,input.provider,actorId]);await client.query(`INSERT INTO audit_events(tenant_id,actor_id,action,resource_type,resource_id,payload) VALUES($1,$2,'did.direct_assigned','did_assignment',$3,$4::jsonb)`,[input.tenantId,actorId,r.rows[0].id,JSON.stringify({reason:input.reason,did:input.did})]);return r.rows[0]}
export async function bindDidFlow(client:pg.PoolClient,tenantId:string,didId:string,input:z.infer<typeof DidFlowBind>,actorId:string){const valid=(await client.query(`SELECT d.id FROM did_assignments d JOIN flow_versions v ON v.flow_id=$2 AND v.version=$3 AND v.state='published' WHERE d.id=$1 AND d.active FOR UPDATE OF d`,[didId,input.flowId,input.flowVersion])).rows[0];if(!valid)throw new Error('active DID or published flow version not found');await client.query(`UPDATE did_flow_bindings SET active=false WHERE did_assignment_id=$1 AND active`,[didId]);const row=(await client.query(`INSERT INTO did_flow_bindings(tenant_id,did_assignment_id,flow_id,flow_version,active) VALUES($1,$2,$3,$4,true) RETURNING id,did_assignment_id AS "didAssignmentId",flow_id AS "flowId",flow_version AS "flowVersion",active`,[tenantId,didId,input.flowId,input.flowVersion])).rows[0];await client.query(`INSERT INTO audit_events(tenant_id,actor_id,action,resource_type,resource_id,payload) VALUES($1,$2,'did.flow_bound','did_assignment',$3,$4::jsonb)`,[tenantId,actorId,didId,JSON.stringify(input)]);return row}
