import {pathToFileURL} from 'node:url';import {pool,withTenant,closeDatabase} from './database.js';import {meetingProvider,type MeetingPayload} from './meetingProvider.js';
type Event={id:string;event_type:'meeting.create'|'meeting.reschedule'|'meeting.cancel';aggregate_id:string;attempts:number};
type Meeting={external_event_id:string|null;title:string;start_at:Date;end_at:Date;timezone:string;attendee_name:string;attendee_address:string;provider_key:string;status:string};
const workerId=process.env.INTEGRATION_WORKER_ID??`integration-${process.pid}`;const pollMs=Math.max(250,Number(process.env.INTEGRATION_WORKER_POLL_MS??1000));let stopping=false;
export function integrationRetryDelay(attempts:number){return Math.min(3600,15*2**Math.max(0,attempts))}
async function tenants(){return (await pool.query<{id:string}>("SELECT id::text FROM tenants WHERE status='active' ORDER BY id")).rows.map(row=>row.id)}
async function claim(tenantId:string){return withTenant(tenantId,async c=>(await c.query<Event>(`WITH picked AS(SELECT e.id FROM integration_events e WHERE e.event_type IN('meeting.create','meeting.reschedule','meeting.cancel') AND e.available_at<=now() AND(e.state='queued' OR(e.state='processing' AND e.lease_until<now())) AND NOT EXISTS(SELECT 1 FROM integration_events earlier WHERE earlier.aggregate_type=e.aggregate_type AND earlier.aggregate_id=e.aggregate_id AND earlier.created_at<e.created_at AND earlier.state IN('queued','processing')) ORDER BY e.created_at FOR UPDATE OF e SKIP LOCKED LIMIT 20) UPDATE integration_events e SET state='processing',lease_owner=$1,lease_until=now()+interval '90 seconds' FROM picked WHERE e.id=picked.id RETURNING e.id,e.event_type,e.aggregate_id,e.attempts`,[workerId])).rows)}
async function processEvent(tenantId:string,event:Event){try{await withTenant(tenantId,async c=>{const meeting=(await c.query<Meeting>(`SELECT m.external_event_id,m.title,m.start_at,m.end_at,m.timezone,m.attendee_name,m.attendee_address,m.status,p.provider_key FROM meetings m JOIN provider_connections p ON p.id=m.provider_connection_id WHERE m.id=$1 AND p.status='active'`,[event.aggregate_id])).rows[0];if(!meeting)throw new Error('meeting or active provider not found');const provider=meetingProvider(meeting.provider_key);if(event.event_type==='meeting.cancel'){if(meeting.external_event_id)await provider.cancel(meeting.external_event_id)}else{const payload:MeetingPayload={title:meeting.title,startAt:meeting.start_at.toISOString(),endAt:meeting.end_at.toISOString(),timezone:meeting.timezone,attendeeName:meeting.attendee_name,attendeeAddress:meeting.attendee_address,...(meeting.external_event_id?{externalEventId:meeting.external_event_id}:{})};const result=event.event_type==='meeting.create'?await provider.create(payload):await provider.update(payload);await c.query(`UPDATE meetings SET external_event_id=$2,join_url=coalesce($3,join_url),status='confirmed',updated_at=now() WHERE id=$1`,[event.aggregate_id,result.externalEventId,result.joinUrl])}await c.query(`UPDATE integration_events SET state='delivered',attempts=attempts+1,delivered_at=now(),lease_owner=NULL,lease_until=NULL,last_error=NULL WHERE id=$1 AND lease_owner=$2`,[event.id,workerId])})}catch(error){const message=error instanceof Error?error.message.slice(0,500):'integration failed';const final=event.attempts+1>=8;await withTenant(tenantId,async c=>{await c.query(`UPDATE integration_events SET state=$2,attempts=attempts+1,available_at=CASE WHEN $2='queued' THEN now()+($3||' seconds')::interval ELSE available_at END,lease_owner=NULL,lease_until=NULL,last_error=$4 WHERE id=$1 AND lease_owner=$5`,[event.id,final?'failed':'queued',String(integrationRetryDelay(event.attempts)),message,workerId]);if(final&&event.event_type!=='meeting.cancel')await c.query(`UPDATE meetings SET status='failed',updated_at=now() WHERE id=$1`,[event.aggregate_id])});console.error('meeting integration failed',{tenantId,eventId:event.id,error:message})}}
async function main(){while(!stopping){for(const tenantId of await tenants()){const events=await claim(tenantId);await Promise.allSettled(events.map(event=>processEvent(tenantId,event)))}await new Promise(resolve=>setTimeout(resolve,pollMs))}await closeDatabase()}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{stopping=true});main().catch(error=>{console.error(error);process.exit(1)})}
