import {z} from 'zod';import type pg from 'pg';
export const MediaNodeCreate=z.object({nodeKey:z.string().regex(/^[a-z0-9][a-z0-9-]{1,62}$/),displayName:z.string().min(2).max(100),privateAddress:z.string().min(3).max(255),region:z.string().min(2).max(50).default('primary'),maxChannels:z.number().int().min(1).max(100000),cpsLimit:z.number().positive().max(10000)});
export const MediaNodeHeartbeat=z.object({nodeKey:z.string().min(2).max(63),activeChannels:z.number().int().min(0),healthy:z.boolean(),metadata:z.record(z.string(),z.unknown()).default({})});
export const MediaNodeReserve=z.object({tenantId:z.string().uuid(),callReference:z.string().min(8).max(200),region:z.string().min(2).max(50).optional()});
export const MediaNodeDrain=z.object({draining:z.boolean()});
export function nodeCanAccept(input:{status:string;lastHeartbeatMs:number;nowMs:number;activeChannels:number;reservations:number;maxChannels:number;recentReservations:number;cpsLimit:number}){return input.status==='active'&&input.nowMs-input.lastHeartbeatMs<=15000&&input.activeChannels+input.reservations<input.maxChannels&&input.recentReservations<input.cpsLimit}
export async function createMediaNode(c:pg.PoolClient,input:z.infer<typeof MediaNodeCreate>){return (await c.query(`INSERT INTO media_nodes(node_key,display_name,private_address,region,max_channels,cps_limit) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,node_key AS "nodeKey",display_name AS "displayName",private_address AS "privateAddress",region,status,max_channels AS "maxChannels",cps_limit::float AS "cpsLimit"`,[input.nodeKey,input.displayName,input.privateAddress,input.region,input.maxChannels,input.cpsLimit])).rows[0]}
export async function heartbeatMediaNode(c:pg.PoolClient,input:z.infer<typeof MediaNodeHeartbeat>){const status=input.healthy?'active':'degraded';const row=(await c.query(`UPDATE media_nodes SET active_channels=$2,status=CASE WHEN status='draining' THEN status ELSE $3 END,last_heartbeat_at=now(),metadata=$4::jsonb,updated_at=now() WHERE node_key=$1 RETURNING id,node_key AS "nodeKey",status,active_channels AS "activeChannels",max_channels AS "maxChannels",last_heartbeat_at AS "lastHeartbeatAt"`,[input.nodeKey,input.activeChannels,status,JSON.stringify(input.metadata)])).rows[0];if(!row)throw new Error('media node is not registered');return row}
export async function listMediaNodes(c:pg.PoolClient){return {items:(await c.query(`SELECT n.id,n.node_key AS "nodeKey",n.display_name AS "displayName",n.private_address AS "privateAddress",n.region,n.status,n.max_channels AS "maxChannels",n.cps_limit::float AS "cpsLimit",n.active_channels AS "activeChannels",n.last_heartbeat_at AS "lastHeartbeatAt",count(r.id) FILTER(WHERE r.state IN('reserved','connected') AND r.expires_at>now())::int AS reservations FROM media_nodes n LEFT JOIN media_node_reservations r ON r.media_node_id=n.id GROUP BY n.id ORDER BY n.region,n.node_key`)).rows}}
export async function setMediaNodeDrain(c:pg.PoolClient,id:string,draining:boolean){const row=(await c.query(`UPDATE media_nodes SET status=CASE WHEN $2 THEN 'draining' WHEN last_heartbeat_at>now()-interval '15 seconds' THEN 'active' ELSE 'offline' END,updated_at=now() WHERE id=$1 RETURNING id,node_key AS "nodeKey",status`,[id,draining])).rows[0];if(!row)throw new Error('media node not found');return row}
export async function reserveMediaNode(c:pg.PoolClient,input:z.infer<typeof MediaNodeReserve>){await c.query(`UPDATE media_node_reservations SET state='expired' WHERE state='reserved' AND expires_at<=now()`);const existing=(await c.query(`SELECT r.id,n.node_key AS "nodeKey",n.private_address AS "privateAddress",r.expires_at AS "expiresAt" FROM media_node_reservations r JOIN media_nodes n ON n.id=r.media_node_id WHERE r.tenant_id=$1 AND r.call_reference=$2 AND r.state IN('reserved','connected')`,[input.tenantId,input.callReference])).rows[0];if(existing)return existing;const node=(await c.query(`SELECT n.id,n.node_key,n.private_address FROM media_nodes n WHERE n.status='active' AND n.last_heartbeat_at>now()-interval '15 seconds' AND($1::text IS NULL OR n.region=$1) AND n.active_channels+(SELECT count(*) FROM media_node_reservations r WHERE r.media_node_id=n.id AND r.state IN('reserved','connected') AND r.expires_at>now())<n.max_channels AND(SELECT count(*) FROM media_node_reservations r WHERE r.media_node_id=n.id AND r.reserved_at>now()-interval '1 second')<n.cps_limit ORDER BY (n.active_channels::numeric/NULLIF(n.max_channels,0)),n.last_heartbeat_at DESC FOR UPDATE OF n SKIP LOCKED LIMIT 1`,[input.region??null])).rows[0];if(!node)throw new Error('no healthy media capacity');return (await c.query(`INSERT INTO media_node_reservations(media_node_id,tenant_id,call_reference,expires_at) VALUES($1,$2,$3,now()+interval '30 seconds') RETURNING id,$4::text AS "nodeKey",$5::text AS "privateAddress",expires_at AS "expiresAt"`,[node.id,input.tenantId,input.callReference,node.node_key,node.private_address])).rows[0]}
export async function releaseMediaReservation(c:pg.PoolClient,id:string){const row=(await c.query(`UPDATE media_node_reservations SET state='released',released_at=now() WHERE id=$1 AND state IN('reserved','connected') RETURNING id,state`,[id])).rows[0];if(!row)throw new Error('active reservation not found');return row}
