import nodemailer from 'nodemailer';import {pool,withTenant,closeDatabase} from './database.js';
type Message={id:string;destination:string;template_key:string;payload:Record<string,unknown>;attempts:number};const workerId=process.env.NOTIFICATION_WORKER_ID??`notify-${process.pid}`;let stopping=false;
const smtpOptions:{host:string;port:number;secure:boolean;pool:boolean;maxConnections:number;auth?:{user:string;pass:string}}={host:process.env.SMTP_HOST??'',port:Number(process.env.SMTP_PORT??587),secure:process.env.SMTP_SECURE==='true',pool:true,maxConnections:5};if(process.env.SMTP_USER)smtpOptions.auth={user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD??''};const transport=nodemailer.createTransport(smtpOptions);
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function render(message:Message){if(message.template_key==='login_code')return {subject:'Your Llamar verification code',text:`Your verification code is ${message.payload.code}. It expires in ${message.payload.expiresMinutes} minutes.`,html:`<h2>Llamar verification</h2><p>Your code is <strong style="font-size:24px">${esc(message.payload.code)}</strong>.</p><p>It expires in ${esc(message.payload.expiresMinutes)} minutes. If you did not request this, ignore this email.</p>`};if(message.template_key==='meeting_pending')return {subject:`Meeting requested: ${message.payload.title}`,text:`Meeting ${message.payload.title} is requested for ${message.payload.startAt} (${message.payload.timezone}).`,html:`<h2>Meeting requested</h2><p><strong>${esc(message.payload.title)}</strong></p><p>${esc(message.payload.startAt)} (${esc(message.payload.timezone)})</p>`};throw new Error(`unknown email template: ${message.template_key}`)}
async function tenants(){return (await pool.query<{id:string}>("SELECT id::text FROM tenants WHERE status='active'")).rows.map(r=>r.id)}
async function claim(tenantId:string){return withTenant(tenantId,async c=>(await c.query<Message>(`WITH picked AS(SELECT id FROM notification_outbox WHERE channel='email' AND state IN('queued','failed') AND available_at<=now() AND(lease_until IS NULL OR lease_until<now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 20) UPDATE notification_outbox n SET state='sending',lease_owner=$1,lease_until=now()+interval '60 seconds' FROM picked WHERE n.id=picked.id RETURNING n.id,n.destination,n.template_key,n.payload,n.attempts`,[workerId])).rows)}
async function deliver(tenantId:string,message:Message){try{const rendered=render(message);const info=await transport.sendMail({from:process.env.SMTP_FROM,to:message.destination,...rendered});await withTenant(tenantId,c=>c.query(`UPDATE notification_outbox SET state='sent',sent_at=now(),provider_message_id=$2,attempts=attempts+1,lease_owner=NULL,lease_until=NULL,last_error=NULL WHERE id=$1 AND lease_owner=$3`,[message.id,info.messageId,workerId]).then(()=>undefined))}catch(error){const delay=Math.min(3600,30*2**message.attempts);await withTenant(tenantId,c=>c.query(`UPDATE notification_outbox SET state='failed',attempts=attempts+1,available_at=now()+($2||' seconds')::interval,lease_owner=NULL,lease_until=NULL,last_error=$3 WHERE id=$1 AND lease_owner=$4`,[message.id,String(delay),error instanceof Error?error.message.slice(0,500):'delivery failed',workerId]).then(()=>undefined))}}
async function main(){if(!process.env.SMTP_HOST)throw new Error('SMTP_HOST is required');while(!stopping){for(const tenant of await tenants()){const messages=await claim(tenant);await Promise.allSettled(messages.map(m=>deliver(tenant,m)))}await new Promise(r=>setTimeout(r,1000))}transport.close();await closeDatabase()}for(const s of ['SIGINT','SIGTERM'] as const)process.on(s,()=>{stopping=true});main().catch(e=>{console.error(e);process.exit(1)});
