import {z} from 'zod';import type pg from 'pg';
export const realtimeProviderKeys=['openai','gemini','xai','nvidia'] as const;
export const RealtimeProviderCreate=z.object({providerKey:z.enum(realtimeProviderKeys),displayName:z.string().min(2).max(100),secretRef:z.string().min(3).max(240),configuration:z.record(z.string(),z.unknown()).default({})});
export const BindRealtimeProvider=z.object({providerConnectionId:z.string().uuid()});
export async function listRealtimeProviders(client:pg.PoolClient){const providers=(await client.query(`SELECT id,provider_key AS "providerKey",display_name AS "displayName",status,capabilities,configuration,created_at AS "createdAt",updated_at AS "updatedAt" FROM provider_connections WHERE category='realtime_ai' ORDER BY display_name`)).rows;return {items:providers,available:realtimeProviderKeys}}
export async function createRealtimeProvider(client:pg.PoolClient,tenantId:string,input:z.infer<typeof RealtimeProviderCreate>,actorId:string){const capabilities=['audio.in','audio.out','barge_in','transcription','multilingual'];const row=(await client.query(`INSERT INTO provider_connections(tenant_id,category,provider_key,display_name,secret_ref,status,capabilities,configuration) VALUES($1,'realtime_ai',$2,$3,$4,'disabled',$5,$6::jsonb) RETURNING id,provider_key AS "providerKey",display_name AS "displayName",status,capabilities,configuration`,[tenantId,input.providerKey,input.displayName,input.secretRef,capabilities,JSON.stringify(input.configuration)])).rows[0];await audit(client,tenantId,actorId,'realtime_provider.created',row.id,{providerKey:input.providerKey});return row}
export async function setRealtimeProviderStatus(client:pg.PoolClient,tenantId:string,id:string,status:'testing'|'active'|'degraded'|'disabled',actorId:string,details:Record<string,unknown>={}){const row=(await client.query(`UPDATE provider_connections SET status=$2,updated_at=now(),configuration=configuration||$3::jsonb WHERE id=$1 AND category='realtime_ai' RETURNING id,provider_key AS "providerKey",display_name AS "displayName",status,configuration,updated_at AS "updatedAt"`,[id,status,JSON.stringify({lastTest:{...details,at:new Date().toISOString()}})])).rows[0];if(!row)throw new Error('realtime provider not found');await audit(client,tenantId,actorId,`realtime_provider.${status}`,id,details);return row}
export async function listVoiceProfiles(client:pg.PoolClient){return {items:(await client.query(`SELECT v.id,v.name,v.primary_locale AS "primaryLocale",v.supported_locales AS "supportedLocales",v.voice_id AS "voiceId",v.status,v.realtime_connection_id AS "realtimeConnectionId",p.provider_key AS "providerKey",p.display_name AS "providerName" FROM ai_voice_profiles v LEFT JOIN provider_connections p ON p.id=v.realtime_connection_id ORDER BY v.name`)).rows}}
export async function bindRealtimeProvider(client:pg.PoolClient,tenantId:string,profileId:string,providerId:string,actorId:string){const row=(await client.query(`UPDATE ai_voice_profiles v SET realtime_connection_id=$2 FROM provider_connections p WHERE v.id=$1 AND p.id=$2 AND p.category='realtime_ai' AND p.status='active' RETURNING v.id,v.name,v.realtime_connection_id AS "realtimeConnectionId",p.provider_key AS "providerKey"`,[profileId,providerId])).rows[0];if(!row)throw new Error('active realtime provider or voice profile not found');await audit(client,tenantId,actorId,'voice_profile.provider_bound',profileId,{providerId});return row}
async function audit(client:pg.PoolClient,tenantId:string,actorId:string,action:string,resourceId:string,payload:Record<string,unknown>){await client.query(`INSERT INTO audit_events(tenant_id,actor_id,action,resource_type,resource_id,payload) VALUES($1,$2,$3,'provider_connection',$4,$5::jsonb)`,[tenantId,actorId,action,resourceId,JSON.stringify(payload)])}
export async function probeRealtimeProvider(key:string){const started=Date.now();if(key==='openai')return readiness(Boolean(process.env.OPENAI_API_KEY),'OPENAI_API_KEY',started);if(key==='gemini')return readiness(Boolean(process.env.GEMINI_API_KEY),'GEMINI_API_KEY',started);if(key==='xai')return readiness(Boolean(process.env.XAI_API_KEY),'XAI_API_KEY',started);if(key==='nvidia'){const urls=[process.env.NVIDIA_ASR_NIM_URL,process.env.NVIDIA_TTS_NIM_URL,process.env.NVIDIA_LLM_NIM_URL];if(urls.some(v=>!v))return readiness(false,'NVIDIA ASR, TTS and LLM NIM URLs',started);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),4000);try{const checks=await Promise.all(urls.slice(0,2).map(url=>fetch(`${url!.replace(/\/$/,'')}/v1/health`,{signal:controller.signal})));return {ready:checks.every(r=>r.ok),latencyMs:Date.now()-started,detail:checks.map(r=>r.status).join(',')}}catch{return {ready:false,latencyMs:Date.now()-started,detail:'NVIDIA health check failed'}}finally{clearTimeout(timeout)}}return readiness(false,'supported provider',started)}
function readiness(ready:boolean,detail:string,started:number){return {ready,latencyMs:Date.now()-started,detail:ready?'configuration present':`${detail} missing`}}
