import Fastify from 'fastify';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import formbody from '@fastify/formbody';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { z } from 'zod';
import {createReadStream} from 'node:fs';import {basename,join} from 'node:path';
import { validateFlow } from './flows.js';
import { can, type Principal, verifyToken } from './security.js';
import { AiVoiceProfile, ProviderConfig, telephonyProviders } from './providers.js';
import { OutboundCallRequest } from './telephony/types.js';
import { telephonyAdapter } from './telephony/registry.js';
import { verifyTwilioSignature } from './telephony/twilio.js';
import { AiAgent, AgentRoute } from './ai/agents.js';
import { renderFreeSwitchXml } from './freeswitch/xml.js';
import { EslClient } from './freeswitch/esl.js';
import { AgentWebRtcRequest, publicWebRtcConfig } from './webrtc.js';
import { closeDatabase, databaseReady, pool, withTenant } from './database.js';
import { CampaignCreate, createCampaign, listCampaigns } from './campaigns.js';
import { ContactListCreate,InlineContactListCreate,createContactList,createInlineContactList,listContactLists } from './contactLists.js';
import { DidDirectAssign, DidRequestCreate, DidReview, createDidRequest, directAssign, listDidAssignments, listDidRequests, reviewDidRequest } from './dids.js';
import { CampaignStart, startCampaign } from './campaignExecution.js';
import { RefreshRequest, RequestCode, VerifyCode, requestLoginCode, revokeRefreshToken, rotateRefreshToken, verifyLoginCode } from './auth.js';
import { FlowCreate, FlowPublish, addFlowVersion, createFlow, listFlows, publishFlow } from './flowRepository.js';
import { PluginCreate, createPlugin, listPlugins } from './plugins.js';
import { MeetingCreate, MeetingUpdate, cancelMeeting, createMeeting, listMeetings,rescheduleMeeting } from './meetings.js';
import { SupervisionStart, startSupervision } from './supervision.js';
import { CreditEntry, addCredit, balance } from './billing.js';
import { ReportExportCreate,ReportRange,dashboard,listReportExports,queueReportExport,recordings,reportExportFile,setLegalHold } from './reports.js';
import { KnowledgeSourceCreate, createKnowledgeSource, searchKnowledge } from './knowledge.js';
import { outboundPlivoXml,outboundTwiml,reconcileProviderStatus,reconcileTwilioStatus,verifyMediaToken } from './callLifecycle.js';
import {BindRealtimeProvider,RealtimeProviderCreate,bindRealtimeProvider,createRealtimeProvider,listRealtimeProviders,listVoiceProfiles,probeRealtimeProvider,setRealtimeProviderStatus} from './realtimeProviders.js';
import {AgentCreate,AgentStatus,VoiceProfileCreate,createAgent,createVoiceProfile,listAgents,setAgentStatus} from './agentStudio.js';
import {CampaignAgentBind,ResolveRoute,RouteCreate,bindCampaignAgent,createRoute,listRoutes,resolveRoute} from './agentRouting.js';
import {callTranscript,liveCalls} from './liveCalls.js';
import {TelephonyProviderCreate,createTelephonyProvider,listTelephonyProviders,testTelephonyProvider} from './telephonyProviders.js';
import {TeamUserCreate,TeamUserUpdate,createTeamUser,listTeam,updateTeamUser} from './team.js';
import {AgentPresenceUpdate,AgentSessionStart,endAgentSession,listAgentPresence,startAgentSession,updateAgentPresence} from './agentPresence.js';
import {DispositionCreate,createDisposition,listDispositions} from './dispositions.js';
import {RecordingUploadHeaders,maxRecordingBytes,recordingMime,recordingObject,recordingPath,storeRecording} from './recordingStorage.js';
import {MediaNodeCreate,MediaNodeDrain,MediaNodeHeartbeat,MediaNodeReserve,createMediaNode,heartbeatMediaNode,listMediaNodes,releaseMediaReservation,reserveMediaNode,setMediaNodeDrain} from './mediaNodes.js';

declare module 'fastify' { interface FastifyRequest { principal: Principal | null } }
const app=Fastify({logger:true,trustProxy:true,bodyLimit:1_048_576});
await app.register(helmet);await app.register(swagger,{openapi:{info:{title:'Llamar Control Plane',version:'0.3.0'}}});await app.register(swaggerUi,{routePrefix:'/docs'});await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(formbody);
app.addContentTypeParser('application/octet-stream',{parseAs:'buffer'},(_req,body,done)=>done(null,body));
app.decorateRequest('principal',null);

app.addHook('preHandler',async(req,reply)=>{
  if(req.url.startsWith('/health')||req.url.startsWith('/docs')||req.url==='/openapi.json'||req.url.startsWith('/v1/webhooks/')||req.url.startsWith('/v1/twiml/')||req.url==='/v1/freeswitch/xml'||req.url.startsWith('/v1/internal/media-nodes/')||req.url==='/v1/internal/ai-route/resolve'||req.url==='/v1/internal/recordings'||['/v1/auth/email/request','/v1/auth/email/verify','/v1/auth/refresh'].includes(req.url)) return;
  const [scheme,token]=(req.headers.authorization??'').split(' ');
  if(scheme!=='Bearer'||!token) return reply.code(401).send({error:'bearer token required'});
  try{req.principal=await verifyToken(token);}catch{return reply.code(401).send({error:'invalid or expired token'});}
});
app.get('/health/live',async()=>({status:'ok'}));
app.get('/health/ready',async(_req,reply)=>{try{return await databaseReady()?{status:'ready'}:reply.code(503).send({status:'not_ready'})}catch{return reply.code(503).send({status:'not_ready'})}});
app.get('/v1/media-nodes',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const c=await pool.connect();try{return await listMediaNodes(c)}finally{c.release()}});
app.post('/v1/media-nodes',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const body=MediaNodeCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid media node',details:body.error.issues});const c=await pool.connect();try{return reply.code(201).send(await createMediaNode(c,body.data))}finally{c.release()}});
app.patch('/v1/media-nodes/:id/drain',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=MediaNodeDrain.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid drain request'});const c=await pool.connect();try{return await setMediaNodeDrain(c,params.data.id,body.data.draining)}catch{return reply.code(404).send({error:'media node not found'})}finally{c.release()}});
app.post('/v1/internal/media-nodes/heartbeat',async(req,reply)=>{const expected=process.env.LLAMAR_INTERNAL_TOKEN??'';if(!expected||req.headers['x-llamar-internal-token']!==expected)return reply.code(401).send({error:'invalid internal token'});const body=MediaNodeHeartbeat.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid heartbeat'});const c=await pool.connect();try{return await heartbeatMediaNode(c,body.data)}catch{return reply.code(404).send({error:'media node not registered'})}finally{c.release()}});
app.post('/v1/internal/media-nodes/reserve',async(req,reply)=>{const expected=process.env.LLAMAR_INTERNAL_TOKEN??'';if(!expected||req.headers['x-llamar-internal-token']!==expected)return reply.code(401).send({error:'invalid internal token'});const body=MediaNodeReserve.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid reservation'});const c=await pool.connect();try{await c.query('BEGIN');const result=await reserveMediaNode(c,body.data);await c.query('COMMIT');return result}catch(error){await c.query('ROLLBACK');return reply.code(503).send({error:error instanceof Error?error.message:'capacity unavailable'})}finally{c.release()}});
app.delete('/v1/internal/media-nodes/reservations/:id',async(req,reply)=>{const expected=process.env.LLAMAR_INTERNAL_TOKEN??'';if(!expected||req.headers['x-llamar-internal-token']!==expected)return reply.code(401).send({error:'invalid internal token'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);if(!params.success)return reply.code(422).send({error:'invalid reservation'});const c=await pool.connect();try{return await releaseMediaReservation(c,params.data.id)}catch{return reply.code(404).send({error:'active reservation not found'})}finally{c.release()}});
app.get('/v1/auth/me',async req=>req.principal);
app.get('/v1/team',async(req,reply)=>{if(!req.principal||!can(req.principal,'users.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listTeam)});
app.post('/v1/team',async(req,reply)=>{if(!req.principal||!can(req.principal,'users.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=TeamUserCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid team user',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createTeamUser(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch{return reply.code(409).send({error:'user already exists'})}});
app.patch('/v1/team/:id',async(req,reply)=>{if(!req.principal||!can(req.principal,'users.edit')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);const body=TeamUserUpdate.safeParse(req.body);if(!p.success||!body.success)return reply.code(422).send({error:'invalid team update'});try{return await withTenant(req.principal.tenantId,c=>updateTeamUser(c,req.principal!.tenantId!,p.data.id,body.data,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'user update failed'})}});
app.post('/v1/auth/email/request',async(req,reply)=>{const parsed=RequestCode.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid request'});try{const result=await withTenant(parsed.data.tenantId,c=>requestLoginCode(c,parsed.data));return reply.code(202).send({accepted:true,...result})}catch(error){req.log.warn(error);return reply.code(429).send({error:'request could not be accepted'})}});
app.post('/v1/auth/email/verify',async(req,reply)=>{const parsed=VerifyCode.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid request'});try{return await withTenant(parsed.data.tenantId,c=>verifyLoginCode(c,parsed.data))}catch{return reply.code(401).send({error:'invalid or expired code'})}});
app.post('/v1/auth/refresh',async(req,reply)=>{const parsed=RefreshRequest.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid request'});try{return await withTenant(parsed.data.tenantId,c=>rotateRefreshToken(c,parsed.data))}catch{return reply.code(401).send({error:'invalid refresh token'})}});
app.post('/v1/auth/logout',async(req,reply)=>{const parsed=RefreshRequest.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid request'});await withTenant(parsed.data.tenantId,c=>revokeRefreshToken(c,parsed.data.refreshToken));return reply.code(204).send()});
app.post('/v1/flows/validate',async(req,reply)=>{
  if(!req.principal||!can(req.principal,'flows.validate')) return reply.code(403).send({error:'insufficient permission'});
  try{const flow=validateFlow(req.body);return {valid:true,nodeCount:flow.nodes.length,edgeCount:flow.edges.length};}
  catch(error){return reply.code(422).send({error:error instanceof Error?error.message:'invalid flow'});}
});
app.post('/v1/flows',async(req,reply)=>{if(!req.principal||!can(req.principal,'flows.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=FlowCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid flow'});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createFlow(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){return reply.code(422).send({error:error instanceof Error?error.message:'flow creation failed'})}});
app.get('/v1/flows',async(req,reply)=>{if(!req.principal||!can(req.principal,'flows.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listFlows)});
app.post('/v1/flows/:id/versions',async(req,reply)=>{if(!req.principal||!can(req.principal,'flows.edit')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=z.object({definition:z.unknown()}).safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid flow version'});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>addFlowVersion(c,req.principal!.tenantId!,params.data.id,body.data.definition,req.principal!.sub)))}catch(error){return reply.code(422).send({error:error instanceof Error?error.message:'version failed'})}});
app.post('/v1/flows/:id/publish',async(req,reply)=>{if(!req.principal||!can(req.principal,'flows.publish')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=FlowPublish.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid publish request'});try{return await withTenant(req.principal.tenantId,c=>publishFlow(c,req.principal!.tenantId!,params.data.id,body.data.version,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'publish failed'})}});
app.get('/v1/providers/telephony',async(req,reply)=>{
  if(!req.principal||!can(req.principal,'plugins.view')) return reply.code(403).send({error:'insufficient permission'});
  return {providers:telephonyProviders};
});
app.get('/v1/providers/telephony/connections',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listTelephonyProviders)});
app.post('/v1/providers/telephony/connections',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.install')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=TelephonyProviderCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid telephony provider',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createTelephonyProvider(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'provider could not be created'})}});
app.post('/v1/providers/telephony/connections/:id/test',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);if(!p.success)return reply.code(422).send({error:'invalid provider'});const result=await withTenant(req.principal.tenantId,c=>testTelephonyProvider(c,req.principal!.tenantId!,p.data.id,req.principal!.sub));return reply.code(result.test.ready?200:503).send(result)});
app.get('/v1/providers/realtime',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listRealtimeProviders)});
app.post('/v1/providers/realtime',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.install')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=RealtimeProviderCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid realtime provider',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createRealtimeProvider(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(409).send({error:'realtime provider could not be created'})}});
app.post('/v1/providers/realtime/:id/test',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);if(!params.success)return reply.code(422).send({error:'invalid provider'});const provider=await withTenant(req.principal.tenantId,async c=>(await c.query(`SELECT provider_key FROM provider_connections WHERE id=$1 AND category='realtime_ai'`,[params.data.id])).rows[0]);if(!provider)return reply.code(404).send({error:'provider not found'});await withTenant(req.principal.tenantId,c=>setRealtimeProviderStatus(c,req.principal!.tenantId!,params.data.id,'testing',req.principal!.sub));const result=await probeRealtimeProvider(provider.provider_key);const updated=await withTenant(req.principal.tenantId,c=>setRealtimeProviderStatus(c,req.principal!.tenantId!,params.data.id,result.ready?'active':'degraded',req.principal!.sub,result));return reply.code(result.ready?200:503).send({...updated,test:result})});
app.post('/v1/providers/realtime/:id/disable',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);if(!params.success)return reply.code(422).send({error:'invalid provider'});return withTenant(req.principal.tenantId,c=>setRealtimeProviderStatus(c,req.principal!.tenantId!,params.data.id,'disabled',req.principal!.sub))});
app.get('/v1/ai/voice-profiles',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listVoiceProfiles)});
app.post('/v1/ai/voice-profiles/:id/realtime-provider',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=BindRealtimeProvider.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid provider binding'});try{return await withTenant(req.principal.tenantId,c=>bindRealtimeProvider(c,req.principal!.tenantId!,params.data.id,body.data.providerConnectionId,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'provider binding failed'})}});
app.post('/v1/plugins',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.install')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=PluginCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid plugin',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createPlugin(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(409).send({error:'plugin could not be installed'})}});
app.get('/v1/plugins',async(req,reply)=>{if(!req.principal||!can(req.principal,'plugins.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listPlugins)});
app.post('/v1/meetings',async(req,reply)=>{if(!req.principal||!can(req.principal,'meetings.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=MeetingCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid meeting',details:parsed.error.issues});try{return reply.code(202).send(await withTenant(req.principal.tenantId,c=>createMeeting(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'meeting failed'})}});
app.get('/v1/meetings',async(req,reply)=>{if(!req.principal||!can(req.principal,'meetings.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listMeetings)});
app.post('/v1/meetings/:id/reschedule',async(req,reply)=>{if(!req.principal||!can(req.principal,'meetings.reschedule')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=MeetingUpdate.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid meeting update'});try{return await withTenant(req.principal.tenantId,c=>rescheduleMeeting(c,params.data.id,body.data))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'reschedule failed'})}});
app.post('/v1/meetings/:id/cancel',async(req,reply)=>{if(!req.principal||!can(req.principal,'meetings.cancel')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);if(!params.success)return reply.code(422).send({error:'invalid meeting'});try{return await withTenant(req.principal.tenantId,c=>cancelMeeting(c,params.data.id))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'cancel failed'})}});
app.post('/v1/providers/telephony/validate',async(req,reply)=>{
  if(!req.principal||!can(req.principal,'plugins.configure')) return reply.code(403).send({error:'insufficient permission'});
  const result=ProviderConfig.safeParse(req.body); if(!result.success)return reply.code(422).send({error:'invalid provider configuration',details:result.error.issues});
  return {valid:true,provider:result.data.provider,countries:result.data.enabledCountries};
});
app.post('/v1/ai/voice-profiles/validate',async(req,reply)=>{
  if(!req.principal||!can(req.principal,'ai_agents.configure')) return reply.code(403).send({error:'insufficient permission'});
  const result=AiVoiceProfile.safeParse(req.body); if(!result.success)return reply.code(422).send({error:'invalid voice profile',details:result.error.issues});
  return {valid:true,primaryLocale:result.data.primaryLocale,supportedLocales:result.data.supportedLocales,avatar:result.data.avatar.characterName};
});
app.post('/v1/ai/voice-profiles',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=VoiceProfileCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid voice profile',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createVoiceProfile(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'voice profile creation failed'})}});
app.post('/v1/calls/outbound',async(req,reply)=>{
  if(!req.principal||!can(req.principal,'calls.originate'))return reply.code(403).send({error:'insufficient permission'});
  const parsed=OutboundCallRequest.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid call request',details:parsed.error.issues});
  try{return reply.code(202).send(await telephonyAdapter('twilio').createCall(parsed.data));}
  catch(error){req.log.error(error);return reply.code(502).send({error:'telephony provider rejected the call'});}
});
app.get('/v1/calls/live',async(req,reply)=>{if(!req.principal||!can(req.principal,'calls.monitor')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const q=z.object({limit:z.coerce.number().int().min(1).max(200).default(50)}).safeParse(req.query);if(!q.success)return reply.code(422).send({error:'invalid pagination'});return withTenant(req.principal.tenantId,c=>liveCalls(c,q.data.limit))});
app.get('/v1/calls/:id/transcript',async(req,reply)=>{if(!req.principal||!can(req.principal,'calls.monitor')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);if(!p.success)return reply.code(422).send({error:'invalid call'});try{return await withTenant(req.principal.tenantId,c=>callTranscript(c,p.data.id))}catch{return reply.code(404).send({error:'call not found'})}});
app.post('/v1/webhooks/twilio/status',async(req,reply)=>{
  const token=process.env.TWILIO_AUTH_TOKEN??'';const base=(process.env.TWILIO_PUBLIC_BASE_URL??'').replace(/\/$/,'');
  const url=`${base}/v1/webhooks/twilio/status`;const params=(req.body??{}) as Record<string,unknown>;
  if(!verifyTwilioSignature(token,req.headers['x-twilio-signature'] as string|undefined,url,params))return reply.code(401).send({error:'invalid Twilio signature'});
  try{req.log.info(await reconcileTwilioStatus(params),'verified call status');return reply.code(204).send()}catch(error){req.log.warn(error);return reply.code(422).send({error:'invalid call event'})}
});
app.post('/v1/webhooks/:provider/status',async(req,reply)=>{const p=z.object({provider:z.enum(['telnyx','plivo','vonage'])}).safeParse(req.params);const q=z.object({token:z.string().min(40)}).safeParse(req.query);if(!p.success||!q.success)return reply.code(401).send({error:'invalid webhook context'});const context=verifyMediaToken(q.data.token);if(!context)return reply.code(401).send({error:'invalid or expired webhook token'});const body=(req.body??{}) as Record<string,unknown>;try{req.log.info(await reconcileProviderStatus(p.data.provider,context.tenantId,context.jobId,body),'verified provider call status');return reply.code(204).send()}catch(error){req.log.warn(error);return reply.code(422).send({error:'invalid call event'})}});
app.post('/v1/twiml/outbound',async(req,reply)=>{const token=process.env.TWILIO_AUTH_TOKEN??'';const base=(process.env.TWILIO_PUBLIC_BASE_URL??'').replace(/\/$/,'');const url=`${base}${req.raw.url}`;const params=(req.body??{}) as Record<string,unknown>;if(!verifyTwilioSignature(token,req.headers['x-twilio-signature'] as string|undefined,url,params))return reply.code(401).send('invalid signature');const query=z.object({tenantId:z.string().uuid(),jobId:z.string().uuid()}).safeParse(req.query);if(!query.success)return reply.code(422).send('invalid call context');try{return reply.type('application/xml').send(outboundTwiml(query.data.tenantId,query.data.jobId))}catch{return reply.code(503).send('voice gateway unavailable')}});
app.post('/v1/twiml/plivo/outbound',async(req,reply)=>{const query=z.object({tenantId:z.string().uuid(),jobId:z.string().uuid(),token:z.string().min(40)}).safeParse(req.query);if(!query.success)return reply.code(422).send('invalid call context');const verified=verifyMediaToken(query.data.token);if(!verified||verified.tenantId!==query.data.tenantId||verified.jobId!==query.data.jobId)return reply.code(401).send('invalid media token');try{return reply.type('application/xml').send(outboundPlivoXml(query.data.tenantId,query.data.jobId))}catch{return reply.code(503).send('voice gateway unavailable')}});
app.post('/v1/ai/agents/validate',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure'))return reply.code(403).send({error:'insufficient permission'});const result=AiAgent.safeParse(req.body);if(!result.success)return reply.code(422).send({error:'invalid AI agent',details:result.error.issues});return {valid:true,trainingModes:[...new Set(result.data.trainingSources.map(s=>s.type))],languages:result.data.languages,maxConcurrentCalls:result.data.maxConcurrentCalls}});
app.get('/v1/ai/agents',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listAgents)});
app.post('/v1/ai/agents',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=AgentCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid AI agent',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createAgent(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'AI agent creation failed'})}});
app.post('/v1/ai/agents/:id/status',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.configure')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=AgentStatus.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid status change'});try{return await withTenant(req.principal.tenantId,c=>setAgentStatus(c,req.principal!.tenantId!,params.data.id,body.data.status,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'status change failed'})}});
app.post('/v1/ai/routes/validate',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.route'))return reply.code(403).send({error:'insufficient permission'});const result=AgentRoute.safeParse(req.body);if(!result.success)return reply.code(422).send({error:'invalid AI route',details:result.error.issues});return {valid:true,did:result.data.did,agentCount:result.data.agentIds.length,strategy:result.data.strategy}});
app.get('/v1/ai/routes',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.route')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listRoutes)});
app.post('/v1/ai/routes',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.route')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=RouteCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid AI route',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createRoute(c,req.principal!.tenantId!,body.data,req.principal!.sub)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'AI route could not be saved'})}});
app.post('/v1/internal/ai-route/resolve',async(req,reply)=>{const expected=process.env.LLAMAR_INTERNAL_TOKEN??'';if(!expected||req.headers['x-llamar-internal-token']!==expected)return reply.code(401).send({error:'invalid internal token'});const body=ResolveRoute.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid route context'});const result=await withTenant(body.data.tenantId,c=>resolveRoute(c,body.data));return result??reply.code(409).send({error:'no available AI agent'})});
app.post('/v1/ai/knowledge',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.knowledge.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=KnowledgeSourceCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid knowledge source',details:parsed.error.issues});try{return reply.code(202).send(await withTenant(req.principal.tenantId,c=>createKnowledgeSource(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(409).send({error:'knowledge source could not be created'})}});
app.get('/v1/ai/knowledge/search',async(req,reply)=>{if(!req.principal||!can(req.principal,'ai_agents.knowledge.search')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const q=z.object({agentId:z.string().uuid(),q:z.string().min(2).max(500)}).safeParse(req.query);if(!q.success)return reply.code(422).send({error:'invalid search'});return withTenant(req.principal.tenantId,c=>searchKnowledge(c,q.data.agentId,q.data.q))});
app.post('/v1/freeswitch/xml',async(req,reply)=>{const expected=process.env.FREESWITCH_XML_CURL_TOKEN??'';const supplied=req.headers['x-llamar-freeswitch-token'];if(!expected||supplied!==expected)return reply.code(401).send('unauthorized');return reply.type('application/xml').send(renderFreeSwitchXml(req.body))});
app.get('/v1/freeswitch/channels',async(req,reply)=>{if(!req.principal||!can(req.principal,'calls.monitor'))return reply.code(403).send({error:'insufficient permission'});try{const client=new EslClient(process.env.FREESWITCH_ESL_HOST??'127.0.0.1',Number(process.env.FREESWITCH_ESL_PORT??8021),process.env.FREESWITCH_ESL_PASSWORD??'');const channels=await client.channels();return {count:channels.length,channels}}catch(error){req.log.error(error);return reply.code(503).send({error:'FreeSWITCH ESL unavailable'})}});
app.post('/v1/supervision',async(req,reply)=>{if(!req.principal||!req.principal.tenantId)return reply.code(403).send({error:'tenant context required'});const parsed=SupervisionStart.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid supervision request'});const permission=`calls.${parsed.data.mode}`;if(!can(req.principal,permission))return reply.code(403).send({error:'insufficient permission'});try{const esl=new EslClient(process.env.FREESWITCH_ESL_HOST??'127.0.0.1',Number(process.env.FREESWITCH_ESL_PORT??8021),process.env.FREESWITCH_ESL_PASSWORD??'');return reply.code(202).send(await withTenant(req.principal.tenantId,c=>startSupervision(c,req.principal!.tenantId!,parsed.data,req.principal!.sub,esl)))}catch(error){req.log.error(error);return reply.code(503).send({error:error instanceof Error?error.message:'supervision failed'})}});
app.post('/v1/agent/webrtc/config',async(req,reply)=>{if(!req.principal||!can(req.principal,'agent.phone.use'))return reply.code(403).send({error:'insufficient permission'});const parsed=AgentWebRtcRequest.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid extension'});try{return publicWebRtcConfig(parsed.data.extension)}catch{return reply.code(503).send({error:'WebRTC is not configured'})}});
app.post('/v1/agent/sessions',async(req,reply)=>{if(!req.principal||!can(req.principal,'agent.phone.use')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=AgentSessionStart.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid agent session'});return reply.code(201).send(await withTenant(req.principal.tenantId,c=>startAgentSession(c,req.principal!.tenantId!,req.principal!.sub,body.data)))});
app.patch('/v1/agent/sessions/:id/presence',async(req,reply)=>{if(!req.principal||!can(req.principal,'agent.phone.use')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);const body=AgentPresenceUpdate.safeParse(req.body);if(!p.success||!body.success)return reply.code(422).send({error:'invalid presence'});try{return await withTenant(req.principal.tenantId,c=>updateAgentPresence(c,req.principal!.sub,p.data.id,body.data.presence))}catch{return reply.code(404).send({error:'active agent session not found'})}});
app.delete('/v1/agent/sessions/:id',async(req,reply)=>{if(!req.principal||!can(req.principal,'agent.phone.use')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);if(!p.success)return reply.code(422).send({error:'invalid session'});try{return await withTenant(req.principal.tenantId,c=>endAgentSession(c,req.principal!.sub,p.data.id))}catch{return reply.code(404).send({error:'active agent session not found'})}});
app.get('/v1/agent/presence',async(req,reply)=>{if(!req.principal||!can(req.principal,'calls.monitor')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listAgentPresence)});
app.post('/v1/calls/dispositions',async(req,reply)=>{if(!req.principal||!can(req.principal,'agent.phone.use')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=DispositionCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid disposition',details:body.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createDisposition(c,req.principal!.tenantId!,req.principal!.sub,body.data)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'disposition failed'})}});
app.get('/v1/calls/dispositions',async(req,reply)=>{if(!req.principal||!can(req.principal,'calls.monitor')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const q=z.object({limit:z.coerce.number().int().min(1).max(200).default(50)}).safeParse(req.query);if(!q.success)return reply.code(422).send({error:'invalid pagination'});return withTenant(req.principal.tenantId,c=>listDispositions(c,q.data.limit))});
app.post('/v1/campaigns',async(req,reply)=>{if(!req.principal||!can(req.principal,'campaigns.create'))return reply.code(403).send({error:'insufficient permission'});if(!req.principal.tenantId)return reply.code(403).send({error:'tenant context required'});const parsed=CampaignCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid campaign',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,client=>createCampaign(client,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(500).send({error:'campaign could not be created'})}});
app.get('/v1/campaigns',async(req,reply)=>{if(!req.principal||!can(req.principal,'campaigns.view'))return reply.code(403).send({error:'insufficient permission'});if(!req.principal.tenantId)return reply.code(403).send({error:'tenant context required'});const query=z.object({limit:z.coerce.number().int().min(1).max(100).default(25),offset:z.coerce.number().int().min(0).default(0)}).safeParse(req.query);if(!query.success)return reply.code(422).send({error:'invalid pagination'});try{return await withTenant(req.principal.tenantId,client=>listCampaigns(client,query.data.limit,query.data.offset))}catch(error){req.log.error(error);return reply.code(500).send({error:'campaigns could not be loaded'})}});
app.post('/v1/campaigns/:id/ai-agent',async(req,reply)=>{if(!req.principal||!can(req.principal,'campaigns.edit')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=CampaignAgentBind.safeParse(req.body);if(!params.success||!body.success)return reply.code(422).send({error:'invalid campaign agent binding'});try{return await withTenant(req.principal.tenantId,c=>bindCampaignAgent(c,req.principal!.tenantId!,params.data.id,body.data.aiAgentId,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'campaign agent binding failed'})}});
app.post('/v1/contact-lists',async(req,reply)=>{if(!req.principal||!can(req.principal,'lists.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=ContactListCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid contact list',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createContactList(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(500).send({error:'contact list could not be created'})}});
app.post('/v1/contact-lists/import',async(req,reply)=>{if(!req.principal||!can(req.principal,'lists.create')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=InlineContactListCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid contacts',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createInlineContactList(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(409).send({error:error instanceof Error?error.message:'contacts could not be imported'})}});
app.get('/v1/contact-lists',async(req,reply)=>{if(!req.principal||!can(req.principal,'lists.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listContactLists)});
app.post('/v1/did-requests',async(req,reply)=>{if(!req.principal||!can(req.principal,'dids.request')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const parsed=DidRequestCreate.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid DID request',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(req.principal.tenantId,c=>createDidRequest(c,req.principal!.tenantId!,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(500).send({error:'DID request could not be created'})}});
app.get('/v1/did-requests',async(req,reply)=>{if(!req.principal||!can(req.principal,'dids.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listDidRequests)});
app.get('/v1/dids',async(req,reply)=>{if(!req.principal||!can(req.principal,'dids.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listDidAssignments)});
app.post('/v1/did-requests/:id/review',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const body=DidReview.safeParse(req.body);const params=z.object({id:z.string().uuid()}).safeParse(req.params);if(!body.success||!params.success)return reply.code(422).send({error:'invalid review'});try{return await withTenant(body.data.tenantId,c=>reviewDidRequest(c,params.data.id,body.data,req.principal!.sub))}catch(error){req.log.error(error);return reply.code(409).send({error:error instanceof Error?error.message:'review failed'})}});
app.post('/v1/dids/direct-assign',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const parsed=DidDirectAssign.safeParse(req.body);if(!parsed.success)return reply.code(422).send({error:'invalid assignment',details:parsed.error.issues});try{return reply.code(201).send(await withTenant(parsed.data.tenantId,c=>directAssign(c,parsed.data,req.principal!.sub)))}catch(error){req.log.error(error);return reply.code(409).send({error:'DID assignment failed'})}});
app.post('/v1/campaigns/:id/start',async(req,reply)=>{if(!req.principal||!can(req.principal,'campaigns.start')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const params=z.object({id:z.string().uuid()}).safeParse(req.params);const body=z.object({maxAttempts:z.number().int().min(1).max(20).default(3)}).safeParse(req.body??{});if(!params.success||!body.success)return reply.code(422).send({error:'invalid campaign start'});try{return await withTenant(req.principal.tenantId,c=>startCampaign(c,req.principal!.tenantId!,CampaignStart.parse({campaignId:params.data.id,maxAttempts:body.data.maxAttempts}),req.principal!.sub))}catch(error){req.log.error(error);return reply.code(409).send({error:error instanceof Error?error.message:'campaign start failed'})}});
app.get('/v1/billing/balance',async(req,reply)=>{if(!req.principal||!can(req.principal,'billing.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,balance)});
app.post('/v1/billing/credits',async(req,reply)=>{if(!req.principal||req.principal.role!=='platform_admin')return reply.code(403).send({error:'platform admin required'});const body=CreditEntry.extend({tenantId:z.string().uuid()}).safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid credit entry'});const {tenantId,...entry}=body.data;try{return await withTenant(tenantId,c=>addCredit(c,tenantId,entry,req.principal!.sub))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'credit failed'})}});
app.get('/v1/reports/dashboard',async(req,reply)=>{if(!req.principal||!can(req.principal,'reports.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const range=ReportRange.safeParse(req.query);if(!range.success)return reply.code(422).send({error:'invalid range'});return withTenant(req.principal.tenantId,c=>dashboard(c,range.data))});
app.post('/v1/reports/exports',async(req,reply)=>{if(!req.principal||!can(req.principal,'reports.export')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const body=ReportExportCreate.safeParse(req.body);if(!body.success)return reply.code(422).send({error:'invalid report export',details:body.error.issues});return reply.code(202).send(await withTenant(req.principal.tenantId,c=>queueReportExport(c,req.principal!.tenantId!,req.principal!.sub,body.data)))});
app.get('/v1/reports/exports',async(req,reply)=>{if(!req.principal||!can(req.principal,'reports.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});return withTenant(req.principal.tenantId,listReportExports)});
app.get('/v1/reports/exports/:id/download',async(req,reply)=>{if(!req.principal||!can(req.principal,'reports.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);if(!p.success)return reply.code(422).send({error:'invalid export'});const item=await withTenant(req.principal.tenantId,c=>reportExportFile(c,p.data.id));if(!item)return reply.code(404).send({error:'export is not ready or has expired'});const safe=basename(item.objectKey);if(safe!==item.objectKey)return reply.code(500).send({error:'invalid export object'});reply.header('content-type',item.format==='csv'?'text/csv; charset=utf-8':'application/json; charset=utf-8').header('content-disposition',`attachment; filename="llamar-${item.id}.${item.format}"`);return reply.send(createReadStream(join(process.env.REPORT_EXPORT_DIR??'/var/lib/llamar/exports',safe)))});
app.get('/v1/recordings',async(req,reply)=>{if(!req.principal||!can(req.principal,'recordings.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(req.query);if(!q.success)return reply.code(422).send({error:'invalid pagination'});return withTenant(req.principal.tenantId,c=>recordings(c,q.data.limit))});
app.post('/v1/internal/recordings',{bodyLimit:maxRecordingBytes()},async(req,reply)=>{const expected=process.env.LLAMAR_INTERNAL_TOKEN??'';if(!expected||req.headers['x-llamar-internal-token']!==expected)return reply.code(401).send({error:'invalid internal token'});const parsed=RecordingUploadHeaders.safeParse({tenantId:req.headers['x-tenant-id'],callSessionId:req.headers['x-call-session-id'],codec:req.headers['x-recording-codec'],sha256:req.headers['x-content-sha256'],retentionDays:req.headers['x-retention-days']});if(!parsed.success||!Buffer.isBuffer(req.body))return reply.code(422).send({error:'invalid recording upload',details:parsed.success?undefined:parsed.error.issues});try{return reply.code(201).send(await withTenant(parsed.data.tenantId,c=>storeRecording(c,parsed.data.tenantId,parsed.data,req.body as Buffer)))}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:'recording upload failed'})}});
app.get('/v1/recordings/:id/media',async(req,reply)=>{if(!req.principal||!can(req.principal,'recordings.view')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);if(!p.success)return reply.code(422).send({error:'invalid recording'});const item=await withTenant(req.principal.tenantId,c=>recordingObject(c,p.data.id));if(!item)return reply.code(404).send({error:'recording not found'});reply.header('content-type',recordingMime(item.codec)).header('content-length',String(item.sizeBytes)).header('content-disposition',`inline; filename="recording-${item.id}.${item.codec}"`).header('cache-control','private, no-store');return reply.send(createReadStream(recordingPath(item.objectKey)))});
app.post('/v1/recordings/:id/legal-hold',async(req,reply)=>{if(!req.principal||!can(req.principal,'recordings.legal_hold')||!req.principal.tenantId)return reply.code(403).send({error:'insufficient permission'});const p=z.object({id:z.string().uuid()}).safeParse(req.params);const b=z.object({hold:z.boolean()}).safeParse(req.body);if(!p.success||!b.success)return reply.code(422).send({error:'invalid legal hold'});try{return await withTenant(req.principal.tenantId,c=>setLegalHold(c,p.data.id,b.data.hold,req.principal!.sub,req.principal!.tenantId!))}catch(error){return reply.code(404).send({error:error instanceof Error?error.message:'recording not found'})}});

app.addHook('onClose',async()=>closeDatabase());

const port=Number(process.env.PORT??18443); const host=process.env.HOST??'0.0.0.0';
app.listen({port,host}).catch(error=>{app.log.error(error);process.exit(1);});
