import {createHash} from 'node:crypto';
import {WebSocketServer,type WebSocket} from 'ws';
import {z} from 'zod';
import {withTenant,closeDatabase} from './database.js';
import {verifyMediaToken} from './callLifecycle.js';
import {createRealtimeProvider,normalizeRealtimeProvider} from './ai/realtime/factory.js';
import type {RealtimeProvider,RealtimeTranscript} from './ai/realtime/types.js';

const Event=z.discriminatedUnion('event',[z.object({event:z.literal('connected')}).passthrough(),z.object({event:z.literal('start'),start:z.object({streamSid:z.string().min(3),customParameters:z.record(z.string(),z.string())})}).passthrough(),z.object({event:z.literal('media'),streamSid:z.string(),media:z.object({payload:z.string(),track:z.string().optional()})}).passthrough(),z.object({event:z.literal('mark')}).passthrough(),z.object({event:z.literal('stop'),streamSid:z.string()}).passthrough()]);
type Session={tenantId:string;jobId:string;id:string;streamSid:string;inputFrames:number;inputBytes:number;outputFrames:number;outputBytes:number;socket:WebSocket;provider:RealtimeProvider;flush?:NodeJS.Timeout};
const sessions=new Map<string,Session>();
async function persistEvent(s:Session,eventType:string,payload:Record<string,unknown>={}){await withTenant(s.tenantId,c=>c.query(`INSERT INTO ai_voice_events(tenant_id,voice_session_id,event_type,payload) VALUES($1,$2,$3,$4::jsonb)`,[s.tenantId,s.id,eventType,JSON.stringify(payload)]).then(()=>undefined))}
async function persistTranscript(s:Session,t:RealtimeTranscript){if(!t.text.trim())return;await withTenant(s.tenantId,c=>c.query(`INSERT INTO ai_voice_transcripts(tenant_id,voice_session_id,speaker,transcript,is_final,provider_item_id) VALUES($1,$2,$3,$4,$5,$6)`,[s.tenantId,s.id,t.speaker,t.text,t.final,t.providerItemId??null]).then(()=>undefined))}
async function start(socket:WebSocket,streamSid:string,params:Record<string,string>){const verified=verifyMediaToken(params.token??'');if(!verified||params.tenantId!==verified.tenantId||params.jobId!==verified.jobId)throw new Error('invalid media token');if(sessions.has(streamSid))throw new Error('duplicate stream');const config=await withTenant(verified.tenantId,async c=>{const result=await c.query(`SELECT j.id,c.ai_agent_id,a.name,a.languages,v.voice_id,v.persona,v.primary_locale,p.provider_key FROM campaign_call_jobs j JOIN campaigns c ON c.id=j.campaign_id LEFT JOIN ai_agents a ON a.id=c.ai_agent_id LEFT JOIN ai_voice_profiles v ON v.id=a.voice_profile_id LEFT JOIN provider_connections p ON p.id=v.realtime_connection_id AND p.category='realtime_ai' AND p.status='active' WHERE j.id=$1`,[verified.jobId]);const job=result.rows[0];if(!job)throw new Error('call job not found');if(!job.ai_agent_id)throw new Error('campaign has no AI agent');const inserted=await c.query(`INSERT INTO ai_voice_sessions(tenant_id,call_job_id,ai_agent_id,provider_stream_id,state,current_speaker) VALUES($1,$2,$3,$4,'active','caller') RETURNING id`,[verified.tenantId,verified.jobId,job.ai_agent_id,streamSid]);return {...job,sessionId:inserted.rows[0].id}});const providerKey=normalizeRealtimeProvider(config.provider_key);let session!:Session;const provider=createRealtimeProvider(providerKey,{voice:config.voice_id||process.env.OPENAI_REALTIME_DEFAULT_VOICE||'marin',safetyIdentifier:createHash('sha256').update(`${verified.tenantId}:${verified.jobId}`).digest('hex'),instructions:`You are ${config.name}. ${config.persona}. Speak naturally and concisely. Primary locale: ${config.primary_locale}. Supported languages: ${(config.languages??[]).join(', ')}. Never claim to be human. Respect consent and stop-call requests immediately.`},{onReady:()=>persistEvent(session,'provider.ready',{provider:providerKey}).catch(console.error),onAudio:payload=>{if(socket.readyState!==socket.OPEN)return;socket.send(JSON.stringify({event:'media',streamSid,media:{payload}}));session.outputFrames++;session.outputBytes+=Buffer.byteLength(payload,'base64')},onTranscript:t=>persistTranscript(session,t).catch(console.error),onInterruption:()=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify({event:'clear',streamSid}));persistEvent(session,'caller.interrupted').catch(console.error)},onEvent:(type,payload)=>persistEvent(session,`provider.${type}`,payload).catch(console.error),onError:error=>{persistEvent(session,'provider.error',{message:error.message}).catch(console.error);if(socket.readyState===socket.OPEN)socket.close(1011,'AI provider error')}});session={tenantId:verified.tenantId,jobId:verified.jobId,id:config.sessionId,streamSid,inputFrames:0,inputBytes:0,outputFrames:0,outputBytes:0,socket,provider};session.flush=setInterval(()=>flush(session).catch(console.error),1000);sessions.set(streamSid,session);await provider.connect();return session}
async function flush(s:Session){const inputFrames=s.inputFrames,inputBytes=s.inputBytes,outputFrames=s.outputFrames,outputBytes=s.outputBytes;s.inputFrames=s.inputBytes=s.outputFrames=s.outputBytes=0;if(!inputFrames&&!outputFrames)return;await withTenant(s.tenantId,c=>c.query(`UPDATE ai_voice_sessions SET input_frames=input_frames+$2,input_bytes=input_bytes+$3,output_frames=output_frames+$4,output_bytes=output_bytes+$5,current_speaker=CASE WHEN $4>0 THEN 'ai' ELSE 'caller' END WHERE id=$1`,[s.id,inputFrames,inputBytes,outputFrames,outputBytes]).then(()=>undefined))}
async function stop(s:Session,state='completed',error?:string){if(s.flush)clearInterval(s.flush);s.provider.close();await flush(s);sessions.delete(s.streamSid);await withTenant(s.tenantId,async c=>{await c.query(`UPDATE ai_voice_sessions SET state=$2,ended_at=now(),last_error=$3 WHERE id=$1`,[s.id,state,error??null]);await c.query(`INSERT INTO ai_voice_events(tenant_id,voice_session_id,event_type,payload) VALUES($1,$2,'session.ended',$3::jsonb)`,[s.tenantId,s.id,JSON.stringify({state})])})}
const wss=new WebSocketServer({port:Number(process.env.VOICE_GATEWAY_PORT??8090),maxPayload:128*1024});wss.on('connection',socket=>{let session:Session|undefined;socket.on('message',async raw=>{try{const event=Event.parse(JSON.parse(raw.toString()));if(event.event==='start')session=await start(socket,event.start.streamSid,event.start.customParameters);else if(event.event==='media'&&session){const bytes=Buffer.byteLength(event.media.payload,'base64');if(bytes>6400)throw new Error('oversized media frame');session.inputFrames++;session.inputBytes+=bytes;session.provider.appendAudio(event.media.payload)}else if(event.event==='stop'&&session){await stop(session);session=undefined}}catch(error){if(session)await stop(session,'failed',error instanceof Error?error.message:'protocol error');socket.close(1008,'invalid media protocol')}});socket.on('close',()=>{if(session)stop(session).catch(console.error)})});
console.log(`Llamar voice gateway listening on ${process.env.VOICE_GATEWAY_PORT??8090}`);for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{wss.close(()=>closeDatabase().finally(()=>process.exit(0))) });
