import {pool,withTenant,closeDatabase} from './database.js';
import {telephonyAdapter} from './telephony/registry.js';
import {mediaToken} from './callLifecycle.js';
type Job={id:string;campaign_id:string;phone_e164:string;attempt_count:number;max_attempts:number;provider_key:string;default_from:string|null};
const workerId=process.env.CAMPAIGN_WORKER_ID??`worker-${process.pid}`;const batch=Math.max(1,Math.min(100,Number(process.env.CAMPAIGN_WORKER_BATCH??10)));const pollMs=Math.max(250,Number(process.env.CAMPAIGN_WORKER_POLL_MS??1000));let stopping=false;
async function activeTenants(){const r=await pool.query<{id:string}>("SELECT id::text FROM tenants WHERE status='active' ORDER BY id");return r.rows.map(x=>x.id)}
async function claim(tenantId:string){return withTenant(tenantId,async c=>(await c.query<Job>(`WITH picked AS (SELECT j.id FROM campaign_call_jobs j JOIN campaigns c ON c.id=j.campaign_id WHERE j.state IN ('ready','retry') AND j.available_at<=now() AND(j.lease_until IS NULL OR j.lease_until<now()) AND(SELECT count(*) FROM campaign_call_jobs active WHERE active.campaign_id=c.id AND active.state IN('leased','dialing','ringing','answered'))<c.channel_limit ORDER BY j.priority,j.created_at FOR UPDATE OF j SKIP LOCKED LIMIT $1) UPDATE campaign_call_jobs j SET state='leased',lease_owner=$2,lease_until=now()+interval '60 seconds',updated_at=now() FROM picked,campaigns c,provider_connections p WHERE j.id=picked.id AND c.id=j.campaign_id AND p.id=c.telephony_provider_id RETURNING j.id,j.campaign_id,(SELECT phone_e164 FROM contacts WHERE id=j.contact_id) AS phone_e164,j.attempt_count,j.max_attempts,p.provider_key,(p.configuration->>'defaultFromNumber') AS default_from`,[batch,workerId])).rows)}
async function complete(tenantId:string,job:Job,providerCallId:string){await withTenant(tenantId,async c=>{await c.query(`UPDATE campaign_call_jobs SET state='dialing',provider_key=$4,provider_call_id=$3,attempt_count=attempt_count+1,lease_owner=NULL,lease_until=NULL,last_error=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2`,[job.id,workerId,providerCallId,job.provider_key]);await c.query(`INSERT INTO audit_events(tenant_id,action,resource_type,resource_id,payload) VALUES($1,'call_job.dialing','campaign_call_job',$2,$3::jsonb)`,[tenantId,job.id,JSON.stringify({providerCallId,provider:job.provider_key})])})}
async function fail(tenantId:string,job:Job,error:unknown){const next=job.attempt_count+1>=job.max_attempts?'failed':'retry';const delay=Math.min(3600,30*2**job.attempt_count);await withTenant(tenantId,c=>c.query(`UPDATE campaign_call_jobs SET state=$2,attempt_count=attempt_count+1,available_at=now()+($3||' seconds')::interval,lease_owner=NULL,lease_until=NULL,last_error=$4,updated_at=now() WHERE id=$1 AND lease_owner=$5`,[job.id,next,String(delay),error instanceof Error?error.message.slice(0,500):'unknown error',workerId]).then(()=>undefined))}
async function processJob(tenantId:string,job:Job){try{const base=(process.env.TWILIO_PUBLIC_BASE_URL??'').replace(/\/$/,'');const instruction=new URL(process.env.TWILIO_INSTRUCTION_URL??`${base}/v1/twiml/outbound`);instruction.searchParams.set('tenantId',tenantId);instruction.searchParams.set('jobId',job.id);const plivoInstruction=new URL(`${base}/v1/twiml/plivo/outbound`);plivoInstruction.searchParams.set('tenantId',tenantId);plivoInstruction.searchParams.set('jobId',job.id);plivoInstruction.searchParams.set('token',mediaToken(tenantId,job.id));const stream=new URL(process.env.VOICE_GATEWAY_WSS_URL??'');stream.searchParams.set('token',mediaToken(tenantId,job.id));stream.searchParams.set('tenantId',tenantId);stream.searchParams.set('jobId',job.id);const launched=await telephonyAdapter(job.provider_key).createCall({to:job.phone_e164,from:job.default_from??undefined,instructionUrl:job.provider_key==='twilio'?instruction.toString():job.provider_key==='plivo'?plivoInstruction.toString():undefined,streamUrl:job.provider_key==='telnyx'?stream.toString():undefined,statusCallbackUrl:`${base}/v1/webhooks/${job.provider_key}/status`,timeoutSeconds:30});await complete(tenantId,job,launched.providerCallId)}catch(error){console.error('campaign call failed',{tenantId,jobId:job.id,error});await fail(tenantId,job,error)}}
async function tick(){for(const tenantId of await activeTenants()){const jobs=await claim(tenantId);await Promise.allSettled(jobs.map(job=>processJob(tenantId,job)))}}
async function main(){while(!stopping){try{await tick()}catch(error){console.error('worker tick failed',error)}await new Promise(resolve=>setTimeout(resolve,pollMs))}await closeDatabase()}
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{stopping=true});main().catch(error=>{console.error(error);process.exit(1)});
