import {pool,withTenant,closeDatabase} from './database.js';
import {telephonyAdapter} from './telephony/registry.js';
import {mediaToken} from './callLifecycle.js';
import {retryDecision} from './callRetryPolicy.js';
import {machineDetectionForMode,type CampaignMode} from './callModePolicy.js';
import {reserveDialSlot} from './dialPacing.js';
type Job={id:string;campaign_id:string;phone_e164:string;attempt_count:number;max_attempts:number;provider_key:string;default_from:string|null;campaign_mode:CampaignMode;provider_count:number;cps_limit:number};
const workerId=process.env.CAMPAIGN_WORKER_ID??`worker-${process.pid}`;const batch=Math.max(1,Math.min(100,Number(process.env.CAMPAIGN_WORKER_BATCH??10)));const pollMs=Math.max(250,Number(process.env.CAMPAIGN_WORKER_POLL_MS??1000));let stopping=false;
async function activeTenants(){const r=await pool.query<{id:string}>("SELECT id::text FROM tenants WHERE status='active' ORDER BY id");return r.rows.map(x=>x.id)}
async function claim(tenantId:string){return withTenant(tenantId,async c=>(await c.query<Job>(`WITH picked AS (SELECT j.id,j.attempt_count,j.campaign_id FROM campaign_call_jobs j JOIN campaigns c ON c.id=j.campaign_id WHERE j.state IN ('ready','retry') AND j.available_at<=now() AND(j.lease_until IS NULL OR j.lease_until<now()) AND(SELECT count(*) FROM campaign_call_jobs active WHERE active.campaign_id=c.id AND active.state IN('leased','dialing','ringing','answered'))<c.channel_limit ORDER BY j.priority,j.created_at FOR UPDATE OF j SKIP LOCKED LIMIT $1) UPDATE campaign_call_jobs j SET state='leased',lease_owner=$2,lease_until=now()+interval '60 seconds',updated_at=now() FROM picked,campaigns c,LATERAL(SELECT routed.* FROM(SELECT p.provider_key,(p.configuration->>'defaultFromNumber') AS default_from,row_number() OVER(ORDER BY r.priority,r.id)::int AS route_number,count(*) OVER()::int AS provider_count FROM campaign_telephony_routes r JOIN provider_connections p ON p.id=r.provider_connection_id AND p.category='telephony' AND p.status='active' WHERE r.campaign_id=picked.campaign_id AND r.enabled)routed WHERE routed.route_number=(picked.attempt_count%routed.provider_count)+1)p WHERE j.id=picked.id AND c.id=j.campaign_id RETURNING j.id,j.campaign_id,(SELECT phone_e164 FROM contacts WHERE id=j.contact_id) AS phone_e164,j.attempt_count,j.max_attempts,p.provider_key,p.default_from,c.mode AS campaign_mode,p.provider_count,c.cps_limit::float AS cps_limit`,[batch,workerId])).rows)}
async function complete(tenantId:string,job:Job,providerCallId:string){await withTenant(tenantId,async c=>{await c.query(`UPDATE campaign_call_jobs SET state='dialing',provider_key=$4,provider_call_id=$3,attempt_count=attempt_count+1,lease_owner=NULL,lease_until=NULL,last_error=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2`,[job.id,workerId,providerCallId,job.provider_key]);await c.query(`INSERT INTO audit_events(tenant_id,action,resource_type,resource_id,payload) VALUES($1,'call_job.dialing','campaign_call_job',$2,$3::jsonb)`,[tenantId,job.id,JSON.stringify({providerCallId,provider:job.provider_key})])})}
async function fail(tenantId:string,job:Job,error:unknown){const decision=retryDecision(job.attempt_count,job.max_attempts,error,job.provider_count);const message=error instanceof Error?error.message.slice(0,500):'unknown error';await withTenant(tenantId,async c=>{await c.query(`UPDATE campaign_call_jobs SET state=$2,attempt_count=attempt_count+1,available_at=CASE WHEN $2='retry' THEN now()+($3||' seconds')::interval ELSE available_at END,lease_owner=NULL,lease_until=NULL,last_error=$4,updated_at=now() WHERE id=$1 AND lease_owner=$5`,[job.id,decision.state,String(decision.delaySeconds),message,workerId]);await c.query(`INSERT INTO audit_events(tenant_id,action,resource_type,resource_id,payload) VALUES($1,'call_job.launch_failed','campaign_call_job',$2,$3::jsonb)`,[tenantId,job.id,JSON.stringify({provider:job.provider_key,state:decision.state,retryReason:decision.reason,retryDelaySeconds:decision.delaySeconds,error:message})])})}
async function pacing(tenantId:string,job:Job){return withTenant(tenantId,async c=>{const slot=await reserveDialSlot(c,tenantId,job.campaign_id,job.cps_limit);if(!slot.admitted)await c.query(`UPDATE campaign_call_jobs SET state='ready',available_at=date_trunc('second',clock_timestamp())+interval '1 second',lease_owner=NULL,lease_until=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2`,[job.id,workerId]);return slot.admitted})}
async function processJob(tenantId:string,job:Job){if(!await pacing(tenantId,job))return;try{const base=(process.env.TWILIO_PUBLIC_BASE_URL??'').replace(/\/$/,'');const instruction=new URL(process.env.TWILIO_INSTRUCTION_URL??`${base}/v1/twiml/outbound`);instruction.searchParams.set('tenantId',tenantId);instruction.searchParams.set('jobId',job.id);const plivoInstruction=new URL(`${base}/v1/twiml/plivo/outbound`);plivoInstruction.searchParams.set('tenantId',tenantId);plivoInstruction.searchParams.set('jobId',job.id);plivoInstruction.searchParams.set('token',mediaToken(tenantId,job.id));const stream=new URL(process.env.VOICE_GATEWAY_WSS_URL??'');stream.searchParams.set('token',mediaToken(tenantId,job.id));stream.searchParams.set('tenantId',tenantId);stream.searchParams.set('jobId',job.id);const callback=new URL(`${base}/v1/webhooks/${job.provider_key}/status`);if(job.provider_key!=='twilio')callback.searchParams.set('token',mediaToken(tenantId,job.id,Math.floor(Date.now()/1000)+86400));const launched=await telephonyAdapter(job.provider_key).createCall({to:job.phone_e164,from:job.default_from??undefined,instructionUrl:job.provider_key==='twilio'?instruction.toString():job.provider_key==='plivo'?plivoInstruction.toString():undefined,streamUrl:['telnyx','vonage'].includes(job.provider_key)?stream.toString():undefined,statusCallbackUrl:callback.toString(),timeoutSeconds:30,machineDetection:machineDetectionForMode(job.campaign_mode)});await complete(tenantId,job,launched.providerCallId)}catch(error){console.error('campaign call failed',{tenantId,jobId:job.id,error});await fail(tenantId,job,error)}}
async function tick(){for(const tenantId of await activeTenants()){const jobs=await claim(tenantId);await Promise.allSettled(jobs.map(job=>processJob(tenantId,job)))}}
async function main(){while(!stopping){try{await tick()}catch(error){console.error('worker tick failed',error)}await new Promise(resolve=>setTimeout(resolve,pollMs))}await closeDatabase()}
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{stopping=true});main().catch(error=>{console.error(error);process.exit(1)});
