BEGIN;
ALTER TABLE recording_objects ADD COLUMN legal_hold boolean NOT NULL DEFAULT false,ADD COLUMN deleted_at timestamptz,ADD COLUMN storage_provider text NOT NULL DEFAULT 'local';
CREATE TABLE credit_accounts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL UNIQUE REFERENCES tenants(id),currency char(3) NOT NULL DEFAULT 'INR',balance_minor bigint NOT NULL DEFAULT 0,reserved_minor bigint NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now(),CHECK(balance_minor>=0),CHECK(reserved_minor>=0),CHECK(reserved_minor<=balance_minor));
CREATE TABLE credit_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),account_id uuid NOT NULL REFERENCES credit_accounts(id),entry_type text NOT NULL CHECK(entry_type IN('credit','debit','reserve','release','adjustment','refund')),amount_minor bigint NOT NULL CHECK(amount_minor>0),currency char(3) NOT NULL,reference_type text NOT NULL,reference_id text NOT NULL,idempotency_key text NOT NULL,actor_id uuid,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,idempotency_key));
CREATE TABLE report_exports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),requested_by uuid NOT NULL,report_type text NOT NULL,format text NOT NULL CHECK(format IN('csv','xlsx','pdf','json')),filters jsonb NOT NULL,state text NOT NULL DEFAULT 'queued' CHECK(state IN('queued','processing','ready','failed','expired')),object_key text,expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE credit_accounts ENABLE ROW LEVEL SECURITY;ALTER TABLE credit_accounts FORCE ROW LEVEL SECURITY;ALTER TABLE credit_ledger ENABLE ROW LEVEL SECURITY;ALTER TABLE credit_ledger FORCE ROW LEVEL SECURITY;ALTER TABLE report_exports ENABLE ROW LEVEL SECURITY;ALTER TABLE report_exports FORCE ROW LEVEL SECURITY;
CREATE POLICY credit_accounts_isolation ON credit_accounts USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);CREATE POLICY credit_ledger_isolation ON credit_ledger USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);CREATE POLICY report_exports_isolation ON report_exports USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE OR REPLACE FUNCTION reject_credit_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'credit ledger is append-only';END;$$;CREATE TRIGGER credit_ledger_no_mutation BEFORE UPDATE OR DELETE ON credit_ledger FOR EACH ROW EXECUTE FUNCTION reject_credit_ledger_mutation();
COMMIT;
