const base='/api';
async function request<T>(path:string,init:RequestInit={}){const response=await fetch(`${base}${path}`,init);const data=response.status===204?null:await response.json();if(!response.ok)throw new Error(data?.error??`Request failed (${response.status})`);return data as T}
export async function requestCode(tenantId:string,email:string){return request<{accepted:boolean;debugCode?:string}>('/v1/auth/email/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantId,email})})}
export async function verifyCode(tenantId:string,email:string,code:string){return request<{accessToken:string;refreshToken:string;expiresIn:number}>('/v1/auth/email/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantId,email,code})})}
export async function dashboard(token:string,from:string,to:string){const q=new URLSearchParams({from,to});return request<{totalCalls:number;answeredCalls:number;failedCalls:number;talkSeconds:number;averagePddSeconds:string}>(`/v1/reports/dashboard?${q}`,{headers:{authorization:`Bearer ${token}`}})}
export type RealtimeProvider={id:string;providerKey:string;displayName:string;status:string;capabilities:string[];configuration:Record<string,unknown>};
export type VoiceProfile={id:string;name:string;primaryLocale:string;supportedLocales:string[];voiceId:string;status:string;realtimeConnectionId:string|null;providerKey:string|null;providerName:string|null};
const auth=(token:string)=>({authorization:`Bearer ${token}`,'content-type':'application/json'});
export async function realtimeProviders(token:string){return request<{items:RealtimeProvider[];available:string[]}>('/v1/providers/realtime',{headers:auth(token)})}
export async function addRealtimeProvider(token:string,input:{providerKey:string;displayName:string;secretRef:string}){return request<RealtimeProvider>('/v1/providers/realtime',{method:'POST',headers:auth(token),body:JSON.stringify({...input,configuration:{}})})}
export async function testRealtimeProvider(token:string,id:string){return request<RealtimeProvider&{test:{ready:boolean;latencyMs:number;detail:string}}>(`/v1/providers/realtime/${id}/test`,{method:'POST',headers:auth(token)})}
export async function voiceProfiles(token:string){return request<{items:VoiceProfile[]}>('/v1/ai/voice-profiles',{headers:auth(token)})}
export async function bindVoiceProvider(token:string,profileId:string,providerConnectionId:string){return request(`/v1/ai/voice-profiles/${profileId}/realtime-provider`,{method:'POST',headers:auth(token),body:JSON.stringify({providerConnectionId})})}
export type AiAgent={id:string;name:string;languages:string[];skills:string[];intents:string[];maxConcurrentCalls:number;emotionAdaptation:boolean;meetingHandoff:boolean;status:string;voiceProfileId:string;voiceProfileName:string;providerKey:string|null;trainingSourceCount:number};
export async function aiAgents(token:string){return request<{items:AiAgent[]}>('/v1/ai/agents',{headers:auth(token)})}
export async function addVoiceProfile(token:string,input:Record<string,unknown>){return request<VoiceProfile>('/v1/ai/voice-profiles',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function addAiAgent(token:string,input:Record<string,unknown>){return request<AiAgent>('/v1/ai/agents',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function setAiAgentStatus(token:string,id:string,status:string){return request(`/v1/ai/agents/${id}/status`,{method:'POST',headers:auth(token),body:JSON.stringify({status})})}
export type AiRoute={id:string;did:string;strategy:string;agentIds:string[];fallbackAgentId:string|null;weights:Record<string,number>;criteria:Record<string,unknown>;enabled:boolean;updatedAt:string;agents:{id:string;name:string;status:string}[]};
export async function aiRoutes(token:string){return request<{items:AiRoute[]}>('/v1/ai/routes',{headers:auth(token)})}
export async function saveAiRoute(token:string,input:Record<string,unknown>){return request<AiRoute>('/v1/ai/routes',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function bindCampaignAiAgent(token:string,campaignId:string,aiAgentId:string|null){return request(`/v1/campaigns/${campaignId}/ai-agent`,{method:'POST',headers:auth(token),body:JSON.stringify({aiAgentId})})}
export type ContactList={id:string;name:string;rowCount:number;status:string;createdAt:string};
export type Campaign={id:string;name:string;mode:string;status:string;contactListId:string|null;contactListName:string|null;aiAgentId:string|null;aiAgentName:string|null;telephonyProviderId:string|null;telephonyProviderName:string|null;telephonyProviderKey:string|null;cpsLimit:string;channelLimit:number;timezone:string;totalJobs:number;activeJobs:number;completedJobs:number;blockedJobs:number;createdAt:string};
export async function contactLists(token:string){return request<{items:ContactList[]}>('/v1/contact-lists',{headers:auth(token)})}
export async function importContactList(token:string,input:Record<string,unknown>){return request<ContactList>('/v1/contact-lists/import',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function campaigns(token:string){return request<{items:Campaign[];total:number}>('/v1/campaigns?limit=100&offset=0',{headers:auth(token)})}
export async function addCampaign(token:string,input:Record<string,unknown>){return request<Campaign>('/v1/campaigns',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function startCampaign(token:string,id:string,maxAttempts=3){return request<{campaignId:string;createdJobs:number;ready:number;policyReview:number;status:string}>(`/v1/campaigns/${id}/start`,{method:'POST',headers:auth(token),body:JSON.stringify({maxAttempts})})}
export type LiveCall={jobId:string;state:string;providerKey:string|null;providerCallId:string|null;updatedAt:string;maskedNumber:string;campaignName:string;aiAgentName:string|null;voiceSessionId:string|null;voiceState:string|null;inputFrames:number;outputFrames:number;currentSpeaker:string|null;startedAt:string|null;endedAt:string|null;durationSeconds:number};
export type TranscriptLine={id:string;speaker:'caller'|'ai'|'human';transcript:string;isFinal:boolean;locale:string|null;emotion:string|null;confidence:string|null;occurredAt:string};
export async function liveCalls(token:string){return request<{items:LiveCall[]}>('/v1/calls/live?limit=100',{headers:auth(token)})}
export async function callTranscript(token:string,jobId:string){return request<{campaignName:string;aiAgentName:string|null;voiceSessionId:string|null;voiceState:string|null;transcript:TranscriptLine[]}>(`/v1/calls/${jobId}/transcript`,{headers:auth(token)})}
export type TelephonyConnection={id:string;providerKey:string;displayName:string;status:string;capabilities:string[];configuration:{defaultFromNumber?:string;lastTest?:{ready:boolean;detail:string;at:string}};policies:{countryCode:string;enabled:boolean;allowedNumberTypes:string[];maxCps:string;maxChannels:number;verifiedCallerIdRequired:boolean}[]};
export async function telephonyConnections(token:string){return request<{available:string[];items:TelephonyConnection[]}>('/v1/providers/telephony/connections',{headers:auth(token)})}
export async function addTelephonyConnection(token:string,input:Record<string,unknown>){return request<TelephonyConnection>('/v1/providers/telephony/connections',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function testTelephonyConnection(token:string,id:string){return request<TelephonyConnection&{test:{ready:boolean;detail:string}}>(`/v1/providers/telephony/connections/${id}/test`,{method:'POST',headers:auth(token)})}
export type TeamUser={id:string;email:string;role:'owner'|'admin'|'supervisor'|'agent'|'auditor';status:'invited'|'active'|'disabled';permissions:string[];createdAt:string;updatedAt?:string};
export async function teamUsers(token:string){return request<{items:TeamUser[]}>('/v1/team',{headers:auth(token)})}
export async function addTeamUser(token:string,input:Pick<TeamUser,'email'|'role'|'status'|'permissions'>){return request<TeamUser>('/v1/team',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export async function updateTeamUser(token:string,id:string,input:Partial<Pick<TeamUser,'role'|'status'|'permissions'>>){return request<TeamUser>(`/v1/team/${id}`,{method:'PATCH',headers:auth(token),body:JSON.stringify(input)})}
export type DidRequest={id:string;requestedNumber:string|null;provider:string;requestType:'new'|'change';status:string;reviewNote:string|null;reviewedAt:string|null;createdAt:string};export type DidAssignment={id:string;did:string;provider:string;active:boolean;assignmentMode:string;sourceRequestId:string|null;createdAt:string};
export async function didRequests(token:string){return request<{items:DidRequest[]}>('/v1/did-requests',{headers:auth(token)})}export async function didAssignments(token:string){return request<{items:DidAssignment[]}>('/v1/dids',{headers:auth(token)})}export async function addDidRequest(token:string,input:Record<string,unknown>){return request<DidRequest>('/v1/did-requests',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
export type FlowVersion={version:number;state:string;sha256:string};export type CallFlow={id:string;name:string;activeVersion:number|null;createdAt:string;versions:FlowVersion[]};
export async function callFlows(token:string){return request<{items:CallFlow[]}>('/v1/flows',{headers:auth(token)})}export async function validateCallFlow(token:string,definition:unknown){return request<{valid:boolean;nodeCount:number;edgeCount:number}>('/v1/flows/validate',{method:'POST',headers:auth(token),body:JSON.stringify(definition)})}export async function createCallFlow(token:string,name:string,definition:unknown){return request('/v1/flows',{method:'POST',headers:auth(token),body:JSON.stringify({name,definition})})}export async function addCallFlowVersion(token:string,id:string,definition:unknown){return request(`/v1/flows/${id}/versions`,{method:'POST',headers:auth(token),body:JSON.stringify({definition})})}export async function publishCallFlow(token:string,id:string,version:number){return request(`/v1/flows/${id}/publish`,{method:'POST',headers:auth(token),body:JSON.stringify({version})})}
export type Recording={id:string;callSessionId:string;codec:string;sizeBytes:number;retentionUntil:string;legalHold:boolean;createdAt:string;direction:string;fromNumber:string;toNumber:string};export async function recordingItems(token:string){return request<{items:Recording[]}>('/v1/recordings?limit=100',{headers:auth(token)})}export async function recordingLegalHold(token:string,id:string,hold:boolean){return request<{id:string;legalHold:boolean}>(`/v1/recordings/${id}/legal-hold`,{method:'POST',headers:auth(token),body:JSON.stringify({hold})})}
export async function recordingMedia(token:string,id:string){const response=await fetch(`${base}/v1/recordings/${id}/media`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Recording media unavailable');return URL.createObjectURL(await response.blob())}
export type ReportExport={id:string;reportType:string;format:string;state:string;errorMessage:string|null;expiresAt:string|null;createdAt:string};export async function reportExports(token:string){return request<{items:ReportExport[]}>('/v1/reports/exports',{headers:auth(token)})}export async function queueReport(token:string,input:{reportType:'call_detail'|'dashboard';format:'csv'|'json';from:string;to:string}){return request<ReportExport>('/v1/reports/exports',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}export async function downloadReport(token:string,id:string){const response=await fetch(`${base}/v1/reports/exports/${id}/download`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Download unavailable');const blob=await response.blob();const disposition=response.headers.get('content-disposition')??'';const name=disposition.match(/filename="([^"]+)"/)?.[1]??`llamar-report-${id}`;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export type PluginConnection={id:string;category:string;providerKey:string;displayName:string;capabilities:string[];status:string};export type Meeting={id:string;title:string;startAt:string;endAt:string;timezone:string;attendeeName:string;attendeeAddress:string;joinUrl:string|null;status:string;callSessionId:string|null;providerName:string;providerKey:string};export async function pluginConnections(token:string){return request<{items:PluginConnection[]}>('/v1/plugins',{headers:auth(token)})}export async function meetings(token:string){return request<{items:Meeting[]}>('/v1/meetings',{headers:auth(token)})}export async function createMeeting(token:string,input:Record<string,unknown>){return request<Meeting>('/v1/meetings',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}export async function cancelMeeting(token:string,id:string){return request(`/v1/meetings/${id}/cancel`,{method:'POST',headers:auth(token)})}
export type WebRtcConfig={wssUrl:string;uri:string;domain:string;iceServers:RTCIceServer[];iceTransportPolicy:RTCIceTransportPolicy;credentialExpiresAt:string};export async function webRtcConfig(token:string,extension:string){return request<WebRtcConfig>('/v1/agent/webrtc/config',{method:'POST',headers:auth(token),body:JSON.stringify({extension})})}
export type AgentSession={id:string;presence:'available'|'busy'|'break'|'wrap_up'|'offline';transport:string;connectedAt:string};export async function startAgentSession(token:string,extension:string){return request<AgentSession>('/v1/agent/sessions',{method:'POST',headers:auth(token),body:JSON.stringify({extension,transport:'webrtc'})})}export async function setAgentPresence(token:string,id:string,presence:'available'|'busy'|'break'|'wrap_up'){return request<AgentSession>(`/v1/agent/sessions/${id}/presence`,{method:'PATCH',headers:auth(token),body:JSON.stringify({presence})})}export async function endAgentSession(token:string,id:string){return request(`/v1/agent/sessions/${id}`,{method:'DELETE',headers:auth(token)})}
export async function createDisposition(token:string,input:Record<string,unknown>){return request('/v1/calls/dispositions',{method:'POST',headers:auth(token),body:JSON.stringify(input)})}
