FROM node:24-alpine AS build
WORKDIR /app
COPY package.json tsconfig.json index.html ./
COPY src ./src
RUN npm install && npm run build

FROM nginx:1.28-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 18080
